import {
  AlertCircle,
  ArrowRight,
  Bell,
  Brain,
  CalendarDays,
  Check,
  ChevronRight,
  Compass,
  Database,
  Download,
  Gamepad2,
  Heart,
  Library,
  Radar,
  RefreshCcw,
  RotateCcw,
  Search,
  Settings2,
  ShieldCheck,
  Sparkles,
  Star,
  X,
} from "lucide-react";

export const tokens = [
  { name: "Background", var: "--background", light: "#f7f8f4", dark: "#070a12" },
  { name: "Foreground", var: "--foreground", light: "#17201d", dark: "#f8fafc" },
  { name: "Card", var: "--card", light: "rgba(255,255,255,0.76)", dark: "rgba(15,23,42,0.76)" },
  { name: "Primary", var: "--primary", light: "#17201d", dark: "#f8fafc" },
  {
    name: "Secondary",
    var: "--secondary",
    light: "rgba(23,32,29,0.06)",
    dark: "rgba(255,255,255,0.07)",
  },
  { name: "Accent", var: "--accent", light: "#0f766e", dark: "#ff6a3d" },
  { name: "Muted", var: "--muted", light: "rgba(23,32,29,0.07)", dark: "rgba(255,255,255,0.07)" },
  { name: "Destructive", var: "--destructive", light: "#be123c", dark: "#fb7185" },
  { name: "Border", var: "--border", light: "rgba(23,32,29,0.14)", dark: "rgba(148,163,184,0.18)" },
  { name: "Input", var: "--input", light: "rgba(255,255,255,0.82)", dark: "rgba(7,10,18,0.66)" },
  { name: "Ring", var: "--ring", light: "rgba(15,118,110,0.85)", dark: "rgba(255,106,61,0.85)" },
  { name: "Ink", var: "--ink", light: "#0d9488", dark: "#38bdf8" },
  { name: "Positive", var: "--positive", light: "#047857", dark: "#34d399" },
  { name: "Warning", var: "--warning", light: "#b45309", dark: "#fbbf24" },
  { name: "Negative", var: "--negative", light: "#be123c", dark: "#fb7185" },
  { name: "Tone Accent", var: "--tone-accent", light: "#0369a1", dark: "#7dd3fc" },
];

export const typography = [
  {
    name: "Eyebrow / Label",
    className: "text-xs font-bold uppercase tracking-[0.12em] text-muted-foreground",
  },
  {
    name: "H1 / Display",
    className: "font-display text-4xl font-black tracking-tight md:text-6xl",
  },
  { name: "H2 / Section", className: "font-display text-3xl font-extrabold tracking-tight" },
  {
    name: "Section Head Title",
    className: "font-display text-4xl font-extrabold tracking-tight md:text-5xl",
  },
  { name: "Card Title", className: "font-display text-xl font-semibold leading-tight" },
  { name: "Body", className: "text-base leading-7" },
  { name: "Body Small", className: "text-sm leading-6 text-muted-foreground" },
  { name: "Mono / Metric", className: "font-mono text-sm" },
];

export const usedIcons: Array<{ name: string; icon: typeof Gamepad2 }> = [
  { name: "AlertCircle", icon: AlertCircle },
  { name: "ArrowRight", icon: ArrowRight },
  { name: "Bell", icon: Bell },
  { name: "Brain", icon: Brain },
  { name: "CalendarDays", icon: CalendarDays },
  { name: "Check", icon: Check },
  { name: "ChevronRight", icon: ChevronRight },
  { name: "Compass", icon: Compass },
  { name: "Database", icon: Database },
  { name: "Download", icon: Download },
  { name: "Gamepad2", icon: Gamepad2 },
  { name: "Heart", icon: Heart },
  { name: "Library", icon: Library },
  { name: "Radar", icon: Radar },
  { name: "RefreshCcw", icon: RefreshCcw },
  { name: "RotateCcw", icon: RotateCcw },
  { name: "Search", icon: Search },
  { name: "Settings2", icon: Settings2 },
  { name: "ShieldCheck", icon: ShieldCheck },
  { name: "Sparkles", icon: Sparkles },
  { name: "Star", icon: Star },
  { name: "X", icon: X },
];
