-- Adds cover art for 139 PSP games from gamesdatabase.org.
-- Images were downloaded from the site's thumbnail URLs (extracted from
-- each game's artwork-box media page) and saved to apps/web/public/covers/games/.
-- 414 of 553 candidates had no scanned box art
-- available on the site (404 for media page or img) and were skipped.
--
-- Idempotent: only applies where cover_url is still empty/null.
begin;

with backfill(game_id, cover_url) as (
  values
    ('football_manager_handheld_2011', '/covers/games/football_manager_handheld_2011.jpg'),
    ('football_manager_handheld_2010', '/covers/games/football_manager_handheld_2010.jpg'),
    ('football_manager_handheld_2009', '/covers/games/football_manager_handheld_2009.jpg'),
    ('yu_gi_oh_5d_s_tag_force_4', '/covers/games/yu_gi_oh_5d_s_tag_force_4.jpg'),
    ('def_jam_fight_for_ny_the_takeover', '/covers/games/def_jam_fight_for_ny_the_takeover.jpg'),
    ('naruto_shippuden_kizuna_drive', '/covers/games/naruto_shippuden_kizuna_drive.jpg'),
    ('fairy_tail_portable_guild', '/covers/games/fairy_tail_portable_guild.jpg'),
    ('tales_of_phantasia_full_voice_edition', '/covers/games/tales_of_phantasia_full_voice_edition.jpg'),
    ('star_wars_lethal_alliance', '/covers/games/star_wars_lethal_alliance.jpg'),
    ('capcom_classics_collection_reloaded', '/covers/games/capcom_classics_collection_reloaded.jpg'),
    ('ys_the_ark_of_napishtim', '/covers/games/ys_the_ark_of_napishtim.jpg'),
    ('capcom_classics_collection_remixed', '/covers/games/capcom_classics_collection_remixed.jpg'),
    ('imagine_champion_rider', '/covers/games/imagine_champion_rider.jpg'),
    ('football_manager_handheld_2012', '/covers/games/football_manager_handheld_2012.jpg'),
    ('lanfeust_of_troy', '/covers/games/lanfeust_of_troy.jpg'),
    ('exit_2', '/covers/games/exit_2.jpg'),
    ('infected', '/covers/games/infected.jpg'),
    ('gradius_collection', '/covers/games/gradius_collection.jpg'),
    ('crush', '/covers/games/crush.jpg'),
    ('smash_court_tennis_3', '/covers/games/smash_court_tennis_3.jpg'),
    ('tna_impact_cross_the_line', '/covers/games/tna_impact_cross_the_line.jpg'),
    ('military_history_commander_europe_at_war', '/covers/games/military_history_commander_europe_at_war.jpg'),
    ('dave_mirra_bmx_challenge', '/covers/games/dave_mirra_bmx_challenge.jpg'),
    ('evangelion_jo', '/covers/games/evangelion_jo.jpg'),
    ('frontier_gate', '/covers/games/frontier_gate.jpg'),
    ('winx_club_join_the_club', '/covers/games/winx_club_join_the_club.jpg'),
    ('armored_core_silent_line_portable', '/covers/games/armored_core_silent_line_portable.jpg'),
    ('williams_pinball_classics', '/covers/games/williams_pinball_classics.jpg'),
    ('eyepet_adventures', '/covers/games/eyepet_adventures.jpg'),
    ('frantix', '/covers/games/frantix.jpg'),
    ('marvel_trading_card_game', '/covers/games/marvel_trading_card_game.jpg'),
    ('nfl_street_3', '/covers/games/nfl_street_3.jpg'),
    ('fired_up', '/covers/games/fired_up.jpg'),
    ('nascar', '/covers/games/nascar.jpg'),
    ('football_manager_handheld', '/covers/games/football_manager_handheld.jpg'),
    ('hannah_montana_rock_out_the_show', '/covers/games/hannah_montana_rock_out_the_show.jpg'),
    ('blitz_overtime', '/covers/games/blitz_overtime.jpg'),
    ('spinout', '/covers/games/spinout.jpg'),
    ('danball_senki', '/covers/games/danball_senki.jpg'),
    ('kenka_bancho_4_ichinen_sensou', '/covers/games/kenka_bancho_4_ichinen_sensou.jpg'),
    ('gunpey', '/covers/games/gunpey.jpg'),
    ('super_hind', '/covers/games/super_hind.jpg'),
    ('cover_girl', '/covers/games/cover_girl.jpg'),
    ('bliss_island', '/covers/games/bliss_island.jpg'),
    ('blokus_portable_steambot_championship', '/covers/games/blokus_portable_steambot_championship.jpg'),
    ('world_of_pool', '/covers/games/world_of_pool.jpg'),
    ('international_athletics', '/covers/games/international_athletics.jpg'),
    ('nba_10_the_inside', '/covers/games/nba_10_the_inside.jpg'),
    ('unchained_blades_exxiv', '/covers/games/unchained_blades_exxiv.jpg'),
    ('world_poker_tour', '/covers/games/world_poker_tour.jpg'),
    ('world_tour_soccer_challenge_edition', '/covers/games/world_tour_soccer_challenge_edition.jpg'),
    ('puzzle_bobble_pocket', '/covers/games/puzzle_bobble_pocket.jpg'),
    ('sd_gundam_g_generation_portable', '/covers/games/sd_gundam_g_generation_portable.jpg'),
    ('gretzky_nhl', '/covers/games/gretzky_nhl.jpg'),
    ('football_manager_handheld_2007', '/covers/games/football_manager_handheld_2007.jpg'),
    ('snoopy_vs_the_red_baron', '/covers/games/snoopy_vs_the_red_baron.jpg'),
    ('talkman', '/covers/games/talkman.jpg'),
    ('football_manager_handheld_2008', '/covers/games/football_manager_handheld_2008.jpg'),
    ('nfl_street_2_unleashed', '/covers/games/nfl_street_2_unleashed.jpg'),
    ('all_kamen_rider_rider_generation_2', '/covers/games/all_kamen_rider_rider_generation_2.jpg'),
    ('wangan_midnight_portable', '/covers/games/wangan_midnight_portable.jpg'),
    ('go_explore', '/covers/games/go_explore.jpg'),
    ('pocket_racers', '/covers/games/pocket_racers.jpg'),
    ('world_snooker_challenge_2005', '/covers/games/world_snooker_challenge_2005.jpg'),
    ('world_snooker_challenge_2007', '/covers/games/world_snooker_challenge_2007.jpg'),
    ('star_soldier', '/covers/games/star_soldier.jpg'),
    ('passport_to_paris', '/covers/games/passport_to_paris.jpg'),
    ('passport_to_barcelona', '/covers/games/passport_to_barcelona.jpg'),
    ('passport_to_rome', '/covers/games/passport_to_rome.jpg'),
    ('downstream_panic', '/covers/games/downstream_panic.jpg'),
    ('tiger_woods_pga_tour', '/covers/games/tiger_woods_pga_tour.jpg'),
    ('daisenryaku_portable', '/covers/games/daisenryaku_portable.jpg'),
    ('passport_to_london', '/covers/games/passport_to_london.jpg'),
    ('memories_off', '/covers/games/memories_off.jpg'),
    ('suzumiya_haruhi_no_yakusoku', '/covers/games/suzumiya_haruhi_no_yakusoku.jpg'),
    ('mystereet_portable', '/covers/games/mystereet_portable.jpg'),
    ('last_escort_club_katze', '/covers/games/last_escort_club_katze.jpg'),
    ('gretzky_nhl_06', '/covers/games/gretzky_nhl_06.jpg'),
    ('nippon_no_asoko_de', '/covers/games/nippon_no_asoko_de.jpg'),
    ('king_of_pool', '/covers/games/king_of_pool.jpg'),
    ('hayarigami_3_keishichou_kaii_jiken_file', '/covers/games/hayarigami_3_keishichou_kaii_jiken_file.jpg'),
    ('passport_to_prague', '/covers/games/passport_to_prague.jpg'),
    ('saki_portable', '/covers/games/saki_portable.jpg'),
    ('juusei_to_diamond', '/covers/games/juusei_to_diamond.jpg'),
    ('little_britain_the_video_game', '/covers/games/little_britain_the_video_game.jpg'),
    ('trick_x_logic_season_1', '/covers/games/trick_x_logic_season_1.jpg'),
    ('world_championship_cards', '/covers/games/world_championship_cards.jpg'),
    ('cake_mania_baker_s_challenge', '/covers/games/cake_mania_baker_s_challenge.jpg'),
    ('jungle_party', '/covers/games/jungle_party.jpg'),
    ('championship_manager', '/covers/games/championship_manager.jpg'),
    ('nhra_drag_racing_countdown_to_the_championship', '/covers/games/nhra_drag_racing_countdown_to_the_championship.jpg'),
    ('passport_to_amsterdam', '/covers/games/passport_to_amsterdam.jpg'),
    ('puzzler_collection', '/covers/games/puzzler_collection.jpg'),
    ('street_cricket_champions', '/covers/games/street_cricket_champions.jpg'),
    ('who_wants_to_be_a_millionaire_party_edition', '/covers/games/who_wants_to_be_a_millionaire_party_edition.jpg'),
    ('telly_addicts', '/covers/games/telly_addicts.jpg'),
    ('ai_mahjong', '/covers/games/ai_mahjong.jpg'),
    ('akatsuki_no_goei_trinity', '/covers/games/akatsuki_no_goei_trinity.jpg'),
    ('ao_no_exorcist_genkoku_no_labyrinth', '/covers/games/ao_no_exorcist_genkoku_no_labyrinth.jpg'),
    ('ape_escape_academy', '/covers/games/ape_escape_academy.jpg'),
    ('bunmei_kaika_aoiza_ibunroku', '/covers/games/bunmei_kaika_aoiza_ibunroku.jpg'),
    ('chandragupta_warrior_prince', '/covers/games/chandragupta_warrior_prince.jpg'),
    ('cart_kings', '/covers/games/cart_kings.jpg'),
    ('clock_zero_shuuen_no_ichibyou_portable', '/covers/games/clock_zero_shuuen_no_ichibyou_portable.jpg'),
    ('fairy_tail_portable_guild_2', '/covers/games/fairy_tail_portable_guild_2.jpg'),
    ('gachitora_abarenbou_kyoushi_in_high_school', '/covers/games/gachitora_abarenbou_kyoushi_in_high_school.jpg'),
    ('gakuen_hetalia_portable', '/covers/games/gakuen_hetalia_portable.jpg'),
    ('genroh', '/covers/games/genroh.jpg'),
    ('glass_heart_princess', '/covers/games/glass_heart_princess.jpg'),
    ('hajime_no_ippo_portable_victorious_spirits', '/covers/games/hajime_no_ippo_portable_victorious_spirits.jpg'),
    ('hayarigami_2_portable_keishichou_kaii_jiken_file', '/covers/games/hayarigami_2_portable_keishichou_kaii_jiken_file.jpg'),
    ('hentai_ouji_to_warawanai_neko', '/covers/games/hentai_ouji_to_warawanai_neko.jpg'),
    ('himawari_pebble_in_the_sky_portable', '/covers/games/himawari_pebble_in_the_sky_portable.jpg'),
    ('hiiro_no_kakera_portable', '/covers/games/hiiro_no_kakera_portable.jpg'),
    ('hisshou_pachinko_pachi_slot_kouryaku_series_portable_vol_1_shinseiki_evangelion_tamashii_no_kiseki', '/covers/games/hisshou_pachinko_pachi_slot_kouryaku_series_portable_vol_1_shinseiki_evangelion_tamashii_no_kiseki.jpg'),
    ('just_english', '/covers/games/just_english.jpg'),
    ('kaeru_batake_de_tsukamaete_portable', '/covers/games/kaeru_batake_de_tsukamaete_portable.jpg'),
    ('kamen_no_maid_guy_boyoyon_battle_royale', '/covers/games/kamen_no_maid_guy_boyoyon_battle_royale.jpg'),
    ('katekyoo_hitman_reborn_battle_arena_2_spirits_burst', '/covers/games/katekyoo_hitman_reborn_battle_arena_2_spirits_burst.jpg'),
    ('kisou_ryouhei_gunhound_ex', '/covers/games/kisou_ryouhei_gunhound_ex.jpg'),
    ('kuon_no_kizuna_sairin_mikotonori_portable', '/covers/games/kuon_no_kizuna_sairin_mikotonori_portable.jpg'),
    ('lisa_to_issho_ni_tairiku_oudan_a_ressha_de_ikou', '/covers/games/lisa_to_issho_ni_tairiku_oudan_a_ressha_de_ikou.jpg'),
    ('lucky_star_net_idol_meister', '/covers/games/lucky_star_net_idol_meister.jpg'),
    ('mashiro_iro_symphony_mutsu_no_hana', '/covers/games/mashiro_iro_symphony_mutsu_no_hana.jpg'),
    ('memories_off_5_encore', '/covers/games/memories_off_5_encore.jpg'),
    ('memories_off_6_t_wave', '/covers/games/memories_off_6_t_wave.jpg'),
    ('pump_it_up_exceed_portable', '/covers/games/pump_it_up_exceed_portable.jpg'),
    ('rebellions_secret_game_2nd_stage', '/covers/games/rebellions_secret_game_2nd_stage.jpg'),
    ('vitamin_r', '/covers/games/vitamin_r.jpg'),
    ('winning_post_6_2006', '/covers/games/winning_post_6_2006.jpg'),
    ('solomon_s_ring_chi_no_shou', '/covers/games/solomon_s_ring_chi_no_shou.jpg'),
    ('dai_2_ji_super_robot_taisen_z_saisei_hen', '/covers/games/dai_2_ji_super_robot_taisen_z_saisei_hen.jpg'),
    ('dies_irae_amantes_amentes', '/covers/games/dies_irae_amantes_amentes.jpg'),
    ('taiko_no_tatsujin_portable_dx', '/covers/games/taiko_no_tatsujin_portable_dx.jpg'),
    ('taiko_no_tatsujin_portable_2', '/covers/games/taiko_no_tatsujin_portable_2.jpg'),
    ('tenchi_no_mon_2_busouden', '/covers/games/tenchi_no_mon_2_busouden.jpg'),
    ('tokimeki_memorial_girl_s_side_premium_3rd_story', '/covers/games/tokimeki_memorial_girl_s_side_premium_3rd_story.jpg'),
    ('mlb_06_the_show', '/covers/games/mlb_06_the_show.jpg'),
    ('musou_orochi_2_special', '/covers/games/musou_orochi_2_special.jpg')
)
update games_library.games g
set cover_url = b.cover_url
from backfill b
where g.game_id = b.game_id
  and (g.cover_url = '' or g.cover_url is null);

commit;
