-- Enriches PS2 (NTSC-U) games with data scraped from psxdatacenter.com's
-- PS2 DataCenter (679 game INFO pages, matched to our catalog by exact
-- normalized title). Rows where the site's release date and our existing
-- release_year differ by more than 3 years were excluded beforehand as
-- likely title collisions with an unrelated game sharing the same name
-- (e.g. "God of War" 2018 reboot vs the 2005 PS2 original) -- see
-- scripts/scrape-psxdatacenter.mjs and scripts/match-psxdatacenter.mjs.
--
-- Genre strings from the site ("Action / RPG", "Driving / Racing", etc.)
-- were mapped to our controlled vocabulary conservatively: exact compound
-- match first (e.g. "action_rpg"), else first segment against the base
-- genre set; anything ambiguous was left unmapped.
--
-- Idempotent: genre only applies where genre_id is still null; company
-- rows use ON CONFLICT DO NOTHING against the existing per-source unique
-- constraint, so re-running is a safe no-op.
begin;

with backfill(game_id, genre_id) as (
  values
    ('ben_10_protector_of_earth', 'action'),
    ('chaos_wars', 'tactical_rpg'),
    ('cyber_troopers_virtual_on_marz', 'action'),
    ('d1_professional_drift_grand_prix_series', 'racing'),
    ('dreamworks_shrek_smash_n_crash_racing', 'racing'),
    ('dreamworks_shrek_the_third', 'action'),
    ('driving_emotion_type_s', 'racing'),
    ('evergrace', 'action'),
    ('ferrari_f355_challenge', 'racing'),
    ('ghosthunter', 'action'),
    ('guilty_gear_x2', 'fighting'),
    ('hannspree_ten_kate_honda_sbk', 'racing'),
    ('headhunter', 'action'),
    ('le_mans_24_hours', 'racing'),
    ('let_s_ride_silver_buckle_stables', 'adventure'),
    ('made_man_confessions_of_the_family_blood', 'action'),
    ('magna_carta_tears_of_blood', 'rpg'),
    ('mercury_meltdown_remix', 'action'),
    ('metropolismania', 'strategy'),
    ('midnight_club_ii', 'racing'),
    ('pac_man_world_2', 'action_platformer'),
    ('paris_dakar_rally', 'racing'),
    ('seek_and_destroy', 'racing'),
    ('sega_classics_collection', 'action'),
    ('shin_megami_tensei_nocturne', 'action_rpg'),
    ('shining_force_exa', 'action_rpg'),
    ('skygunner', 'action'),
    ('steambot_chronicles', 'action_rpg'),
    ('strawberry_shortcake_the_sweet_dreams_game', 'action_adventure'),
    ('the_nightmare_of_druaga_fushigino_dungeon', 'action_rpg')
)
update games_library.games g
set genre_id = b.genre_id
from backfill b
where g.game_id = b.game_id
  and g.genre_id is null;

insert into games_library.game_companies (game_id, company_name, role, source, source_key)
select game_id, company_name, role, 'psxdatacenter', source_key
from (
  values
    ('18_wheeler_american_pro_trucker', 'Acclaim Studios Cheltenham', 'developer', 'SLUS-20210'),
    ('18_wheeler_american_pro_trucker', 'Acclaim Entertainment, Inc', 'publisher', 'SLUS-20210'),
    ('24_the_game', 'SCEE Cambridge Studios', 'developer', 'SLUS-21268'),
    ('24_the_game', 'Sony', 'publisher', 'SLUS-21268'),
    ('25_to_life', 'Avalanche Software / Ritual Entertainment', 'developer', 'SLUS-21016'),
    ('25_to_life', 'Eidos Interactive', 'publisher', 'SLUS-21016'),
    ('50_cent_bulletproof', 'Genuine Games', 'developer', 'SLUS-21315'),
    ('50_cent_bulletproof', 'Vivendi Universal Games', 'publisher', 'SLUS-21315'),
    ('187_ride_or_die', 'Ubisoft Paris', 'developer', 'SLUS-21116'),
    ('187_ride_or_die', 'Ubi Soft Entertainment Software', 'publisher', 'SLUS-21116'),
    ('ace_combat_5_the_unsung_war', 'Project Aces', 'developer', 'SLUS-20851'),
    ('ace_combat_5_the_unsung_war', 'Namco', 'publisher', 'SLUS-20851'),
    ('aeon_flux', 'Terminal Reality', 'developer', 'SLUS-21205'),
    ('aeon_flux', 'Majesco', 'publisher', 'SLUS-21205'),
    ('airforce_delta_strike', 'Konami Computer Entertainment Studios, Inc', 'developer', 'SLUS-20346'),
    ('airforce_delta_strike', 'Konami', 'publisher', 'SLUS-20346'),
    ('airblade', 'Criterion Games', 'developer', 'SLUS-20346'),
    ('airblade', 'Namco', 'publisher', 'SLUS-20346'),
    ('alias', 'Acclaim Studios Cheltenham', 'developer', 'SLUS-20673'),
    ('alias', 'Acclaim', 'publisher', 'SLUS-20673'),
    ('ape_escape_pumped_primed', 'Sony Computer Entertainment Inc. (Japan)', 'developer', 'SLUS-21096'),
    ('ape_escape_pumped_primed', 'Ubisoft Entertainment', 'publisher', 'SLUS-21096'),
    ('ape_escape_3', 'Sony', 'developer', 'SCUS-97501'),
    ('ape_escape_3', 'Sony', 'publisher', 'SCUS-97501'),
    ('aqua_aqua', 'Zed Two Limited', 'developer', 'SLUS-20162'),
    ('aqua_aqua', 'The 3DO Company', 'publisher', 'SLUS-20162'),
    ('arcana_heart', 'Examu Inc', 'developer', 'SLUS-21720'),
    ('arcana_heart', 'Atlus', 'publisher', 'SLUS-21720'),
    ('arctic_thunder', 'Inland Productions', 'developer', 'SLUS-20217'),
    ('arctic_thunder', 'Midway', 'publisher', 'SLUS-20217'),
    ('art_of_fighting_anthology', 'SNK Playmore USA', 'developer', 'SLUS-21487'),
    ('art_of_fighting_anthology', 'SNK Playmore', 'publisher', 'SLUS-21487'),
    ('arthur_and_the_invisibles_the_game', 'Etranges Libellules', 'developer', 'SLUS-21305'),
    ('arthur_and_the_invisibles_the_game', 'Atari', 'publisher', 'SLUS-21305'),
    ('asterix_obelix_kick_buttix', 'Etranges Libellules', 'developer', 'SLUS-20866'),
    ('asterix_obelix_kick_buttix', 'Atari', 'publisher', 'SLUS-20866'),
    ('astro_boy', 'Sonic Team', 'developer', 'SLUS-20867'),
    ('astro_boy', 'Sega', 'publisher', 'SLUS-20867'),
    ('atelier_iris_eternal_mana', 'Gust Co., Ltd', 'developer', 'SLUS-21113'),
    ('atelier_iris_eternal_mana', 'NIS America', 'publisher', 'SLUS-21113'),
    ('athens_2004', 'Eurocom', 'developer', 'SCUS-97379'),
    ('athens_2004', '989 Studios', 'publisher', 'SCUS-97379'),
    ('auto_modellista', 'Capcom', 'developer', 'SLUS-20642'),
    ('auto_modellista', 'Capcom', 'publisher', 'SLUS-20642'),
    ('avatar_the_last_airbender_into_the_inferno', 'THQ Australia', 'developer', 'SLUS-21804'),
    ('avatar_the_last_airbender_into_the_inferno', 'THQ', 'publisher', 'SLUS-21804'),
    ('b_boy', 'FreeStyleGames', 'developer', 'SLUS-21761'),
    ('b_boy', 'Evolved Games', 'publisher', 'SLUS-21761'),
    ('barbarian', 'Saffire Corporation', 'developer', 'SLUS-20136'),
    ('barbarian', 'Titus', 'publisher', 'SLUS-20136'),
    ('batman_begins', 'Eurocom Developments Ltd', 'developer', 'SLUS-21198'),
    ('batman_begins', 'Electronic Arts', 'publisher', 'SLUS-21198'),
    ('batman_vengeance', 'Ubisoft', 'developer', 'SLUS-20226'),
    ('batman_vengeance', 'Ubisoft', 'publisher', 'SLUS-20226'),
    ('battlefield_2_modern_combat', 'Digital Illusions CE AB', 'developer', 'SLUS-21026'),
    ('battlefield_2_modern_combat', 'EA Games', 'publisher', 'SLUS-21026'),
    ('beat_down_fists_of_vengeance', 'Cavia, Inc', 'developer', 'SLUS-21150'),
    ('beat_down_fists_of_vengeance', 'Capcom', 'publisher', 'SLUS-21150'),
    ('ben_10_protector_of_earth', 'High Voltage Software', 'developer', 'SLUS-21661'),
    ('ben_10_protector_of_earth', 'D3 Publisher', 'publisher', 'SLUS-21661'),
    ('black', 'Criterion Studios', 'developer', 'SLUS-21376'),
    ('black', 'Electronic Arts', 'publisher', 'SLUS-21376'),
    ('bloody_roar_3', 'Eighting Co., Ltd. (8ing)', 'developer', 'SLUS-20212'),
    ('bloody_roar_3', 'Activision', 'publisher', 'SLUS-20212'),
    ('bmx_xxx', 'Z-Axis, Ltd', 'developer', 'SLUS-20415'),
    ('bmx_xxx', 'Acclaim', 'publisher', 'SLUS-20415'),
    ('brave_the_search_for_spirit_dancer', 'VIS entertainment plc', 'developer', 'SLUS-21127'),
    ('brave_the_search_for_spirit_dancer', 'Evolved Games / SouthPeak Games', 'publisher', 'SLUS-21127'),
    ('breath_of_fire_dragon_quarter', 'Capcom Co., Ltd', 'developer', 'SLUS-20499'),
    ('breath_of_fire_dragon_quarter', 'Capcom', 'publisher', 'SLUS-20499'),
    ('breeders_cup_world_thoroughbred_championships', '4J Studios Ltd', 'developer', 'SLUS-21195'),
    ('breeders_cup_world_thoroughbred_championships', 'Bethesda Softworks LLC', 'publisher', 'SLUS-21195'),
    ('brothers_in_arms_earned_in_blood', 'Gearbox Software LLC', 'developer', 'SLUS-21310'),
    ('brothers_in_arms_earned_in_blood', 'Ubisoft, Inc', 'publisher', 'SLUS-21310'),
    ('buffy_the_vampire_slayer_chaos_bleeds', 'Eurocom Developments Ltd', 'developer', 'SLUS-20566'),
    ('buffy_the_vampire_slayer_chaos_bleeds', 'Vivendi Universal Games', 'publisher', 'SLUS-20566'),
    ('bujingai_the_forsaken_city', 'RED Entertainment', 'developer', 'SLUS-20895'),
    ('bujingai_the_forsaken_city', 'BAM! Entertainment, Inc', 'publisher', 'SLUS-20895'),
    ('bully', 'Rockstar Games', 'developer', 'SLUS-21269'),
    ('bully', 'Rockstar Games', 'publisher', 'SLUS-21269'),
    ('call_of_duty_finest_hour', 'Spark Unlimited', 'developer', 'SLUS-20725'),
    ('call_of_duty_finest_hour', 'Activision', 'publisher', 'SLUS-20725'),
    ('call_of_duty_2_big_red_one', 'Treyarch', 'developer', 'SLUS-21228'),
    ('call_of_duty_2_big_red_one', 'Activision', 'publisher', 'SLUS-21228'),
    ('call_of_duty_3', 'Treyarch', 'developer', 'SLUS-21426'),
    ('call_of_duty_3', 'Activision', 'publisher', 'SLUS-21426'),
    ('carmen_sandiego_the_secret_of_the_stolen_drums', 'Artificial Mind and Movement (A2M)', 'developer', 'SLUS-20849'),
    ('carmen_sandiego_the_secret_of_the_stolen_drums', 'BAM! Entertainment, Inc', 'publisher', 'SLUS-20849'),
    ('castlevania_lament_of_innocence', 'KCET', 'developer', 'SLUS-20733'),
    ('castlevania_lament_of_innocence', 'Konami', 'publisher', 'SLUS-20733'),
    ('champions_of_norrath', 'Snowblind Studios, Inc', 'developer', 'SLUS-20565'),
    ('champions_of_norrath', 'Sony', 'publisher', 'SLUS-20565'),
    ('chaos_legion', 'Capcom', 'developer', 'SLUS-20695'),
    ('chaos_legion', 'Capcom', 'publisher', 'SLUS-20695'),
    ('chaos_wars', 'Idea Factory', 'developer', 'SLUS-21722'),
    ('chaos_wars', 'O3 Entertainment', 'publisher', 'SLUS-21722'),
    ('clock_tower_3', 'Capcom', 'developer', 'SLUS-20633'),
    ('clock_tower_3', 'Capcom', 'publisher', 'SLUS-20633'),
    ('codename_kids_next_door_operation_v_i_d_e_o_g_a_m_e', 'High Voltage Software, Inc', 'developer', 'SLUS-21155'),
    ('codename_kids_next_door_operation_v_i_d_e_o_g_a_m_e', 'Global Star Software Ltd', 'publisher', 'SLUS-21155'),
    ('cold_fear', 'Darkworks', 'developer', 'SLUS-21047'),
    ('cold_fear', 'Ubisoft', 'publisher', 'SLUS-21047'),
    ('commandos_strike_force', 'Pyro Studios', 'developer', 'SLUS-21103'),
    ('commandos_strike_force', 'Eidos Interactive', 'publisher', 'SLUS-21103'),
    ('conflict_vietnam', 'Pivotal Games Ltd', 'developer', 'SLUS-21045'),
    ('conflict_vietnam', 'Global Star Software Ltd', 'publisher', 'SLUS-21045'),
    ('contra_shattered_soldier', 'Konami Computer Entertainment Tokyo (KCET)', 'developer', 'SLUS-20306'),
    ('contra_shattered_soldier', 'Konami', 'publisher', 'SLUS-20306'),
    ('cool_boarders_2001', 'Idol Minds, L.L.C', 'developer', 'SCUS-97108'),
    ('cool_boarders_2001', 'Sony', 'publisher', 'SCUS-97108'),
    ('corvette', 'Steel Monkeys', 'developer', 'SLUS-20858'),
    ('corvette', 'Take 2 Interactive / Global Star Software Inc', 'publisher', 'SLUS-20858'),
    ('corvette_evolution_gt', 'Milestone s.r.l', 'developer', 'SLUS-21499'),
    ('corvette_evolution_gt', 'Valcon Games, LLC', 'publisher', 'SLUS-21499'),
    ('crash_bandicoot_the_wrath_of_cortex', 'Traveller''s Tales', 'developer', 'SLUS-20238'),
    ('crash_bandicoot_the_wrath_of_cortex', 'Universal Interactive Studios', 'publisher', 'SLUS-20238'),
    ('crash_nitro_kart', 'Vicarious Visions, Inc', 'developer', 'SLUS-20649'),
    ('crash_nitro_kart', 'Vivendi Universal Games', 'publisher', 'SLUS-20649'),
    ('crash_of_the_titans', 'Radical Entertainment', 'developer', 'SLUS-21583'),
    ('crash_of_the_titans', 'Sierra Entertainment', 'publisher', 'SLUS-21583'),
    ('crash_twinsanity', 'Traveller''s Tales', 'developer', 'SLUS-20909'),
    ('crash_twinsanity', 'Vivendi Universal Games', 'publisher', 'SLUS-20909'),
    ('crouching_tiger_hidden_dragon', 'Genki Co', 'developer', 'SLUS-20523'),
    ('crouching_tiger_hidden_dragon', 'Ubisoft', 'publisher', 'SLUS-20523'),
    ('csi_3_dimensions_of_murder', 'Ubisoft Bulgaria', 'developer', 'SLUS-21655'),
    ('csi_3_dimensions_of_murder', 'Ubisoft', 'publisher', 'SLUS-21655'),
    ('cy_girls', 'Konami Computer Entertainment Japan Co., Ltd. (KCEJ)', 'developer', 'SLUS-20697SLUS-20854'),
    ('cy_girls', 'Konami', 'publisher', 'SLUS-20697SLUS-20854'),
    ('cyber_troopers_virtual_on_marz', 'Hitmaker Co., Ltd', 'developer', 'SLUS-20674'),
    ('cyber_troopers_virtual_on_marz', 'Sega', 'publisher', 'SLUS-20674'),
    ('d1_professional_drift_grand_prix_series', 'Yuke''s Co. Ltd', 'developer', 'SLUS-21416'),
    ('d1_professional_drift_grand_prix_series', 'Yuke''s Company of America', 'publisher', 'SLUS-21416'),
    ('dance_dance_revolution_supernova', 'Konami Digital Entertainment, Inc. (KDEI)', 'developer', 'SLUS-21377'),
    ('dance_dance_revolution_supernova', 'Konami', 'publisher', 'SLUS-21377'),
    ('dancing_with_the_stars', 'Zoe Mode', 'developer', 'SLUS-21676'),
    ('dancing_with_the_stars', 'Activision Value Publishing Inc', 'publisher', 'SLUS-21676'),
    ('dark_cloud', 'Level 5', 'developer', 'SCUS-97111'),
    ('dark_cloud', 'Sony', 'publisher', 'SCUS-97111'),
    ('dark_cloud_2', 'Level-5', 'developer', 'SCUS-97213'),
    ('dark_cloud_2', 'Sony Computer Entertainment', 'publisher', 'SCUS-97213'),
    ('dawn_of_mana', 'Square Enix', 'developer', 'SLUS-21574'),
    ('dawn_of_mana', 'Square Enix', 'publisher', 'SLUS-21574'),
    ('dead_or_alive_2_hardcore', 'Team Ninja', 'developer', 'SLUS-20071'),
    ('dead_or_alive_2_hardcore', 'Tecmo', 'publisher', 'SLUS-20071'),
    ('dead_to_rights', 'Namco', 'developer', 'SLUS-20220'),
    ('dead_to_rights', 'Namco', 'publisher', 'SLUS-20220'),
    ('def_jam_fight_for_ny', 'Aki Corp', 'developer', 'SLUS-21004'),
    ('def_jam_fight_for_ny', 'EA Games', 'publisher', 'SLUS-21004'),
    ('def_jam_vendetta', 'AKI Corporation', 'developer', 'SLUS-20639'),
    ('def_jam_vendetta', 'EA Sports Big', 'publisher', 'SLUS-20639'),
    ('delta_force_black_hawk_down', 'Rebellion', 'developer', 'SLUS-21124'),
    ('delta_force_black_hawk_down', 'NovaLogic, Inc', 'publisher', 'SLUS-21124'),
    ('despicable_me_the_game', 'Monkey Bar Games', 'developer', 'SLUS-21933'),
    ('despicable_me_the_game', 'D3 Publisher', 'publisher', 'SLUS-21933'),
    ('destroy_all_humans', 'Pandemic Studio Pty. Ltd', 'developer', 'SLUS-20945'),
    ('destroy_all_humans', 'THQ', 'publisher', 'SLUS-20945'),
    ('deus_ex_the_conspiracy', 'Ion Storm', 'developer', 'SLUS-20111'),
    ('deus_ex_the_conspiracy', 'Eidos Interactive', 'publisher', 'SLUS-20111'),
    ('devil_kings', 'Capcom Production Studio 4', 'developer', 'SLUS-21297'),
    ('devil_kings', 'Capcom', 'publisher', 'SLUS-21297'),
    ('devil_may_cry', 'Capcom Co., Ltd', 'developer', 'SLUS-20216'),
    ('devil_may_cry', 'Capcom', 'publisher', 'SLUS-20216'),
    ('devil_may_cry_2', 'Capcom', 'developer', 'SLUS-20484SLUS-20627'),
    ('devil_may_cry_2', 'Capcom', 'publisher', 'SLUS-20484SLUS-20627'),
    ('digimon_rumble_arena_2', 'Black Ship Games', 'developer', 'SLUS-21067'),
    ('digimon_rumble_arena_2', 'Bandai', 'publisher', 'SLUS-21067'),
    ('digimon_world_4', 'BEC Co., Ltd', 'developer', 'SLUS-20836'),
    ('digimon_world_4', 'Bandai', 'publisher', 'SLUS-20836'),
    ('dino_stalker', 'Capcom', 'developer', 'SLUS-20485'),
    ('dino_stalker', 'Capcom', 'publisher', 'SLUS-20485'),
    ('disaster_report', 'Irem Software Engineering, Inc', 'developer', 'SLUS-20561'),
    ('disaster_report', 'Agetec Inc', 'publisher', 'SLUS-20561'),
    ('disney_golf', 'T&E Soft, Inc', 'developer', 'SLUS-20532'),
    ('disney_golf', 'Electronic Arts', 'publisher', 'SLUS-20532'),
    ('disney_s_chicken_little', 'Avalanche Software', 'developer', 'SLUS-21088'),
    ('disney_s_chicken_little', 'Disney Interactive Studios', 'publisher', 'SLUS-21088'),
    ('disney_s_extreme_skate_adventure', 'Toys for Bob', 'developer', 'SLUS-20607'),
    ('disney_s_extreme_skate_adventure', 'Activision, Inc', 'publisher', 'SLUS-20607'),
    ('disney_s_kim_possible_what_s_the_switch', 'Artificial Mind And Move (A2M)', 'developer', 'SLUS-21437'),
    ('disney_s_kim_possible_what_s_the_switch', 'Disney Interactive', 'publisher', 'SLUS-21437'),
    ('disney_s_meet_the_robinsons', 'Avalanche Software', 'developer', 'SLUS-21453'),
    ('disney_s_meet_the_robinsons', 'Disney Interactive', 'publisher', 'SLUS-21453'),
    ('disney_s_pk_out_of_the_shadows', 'Ubisoft', 'developer', 'SLUS-20478'),
    ('disney_s_pk_out_of_the_shadows', 'Ubisoft / Disney Interactive', 'publisher', 'SLUS-20478'),
    ('disney_s_tarzan_untamed', 'Ubisoft Montreal Studios', 'developer', 'SLUS-20076'),
    ('disney_s_tarzan_untamed', 'Ubisoft / Disney Interactive', 'publisher', 'SLUS-20076'),
    ('downhill_domination', 'Incog Inc. Entertainment', 'developer', 'SCUS-97177'),
    ('downhill_domination', 'Codemasters', 'publisher', 'SCUS-97177'),
    ('dr_muto', 'Midway Games West Inc', 'developer', 'SLUS-20458'),
    ('dr_muto', 'Midway', 'publisher', 'SLUS-20458'),
    ('dr_seuss_the_cat_in_the_hat', 'Magenta Software / Digital Eclipse', 'developer', 'SLUS-20797'),
    ('dr_seuss_the_cat_in_the_hat', 'Vivendi Universal Games', 'publisher', 'SLUS-20797'),
    ('dragon_ball_z_budokai', 'Dimps Corporation', 'developer', 'SLUS-20591'),
    ('dragon_ball_z_budokai', 'Infogrames', 'publisher', 'SLUS-20591'),
    ('dragon_ball_z_budokai_2', 'Dimps Corporation', 'developer', 'SLUS-20779'),
    ('dragon_ball_z_budokai_2', 'Atari', 'publisher', 'SLUS-20779'),
    ('dragon_quest_viii', 'Level 5', 'developer', 'SLUS-21207'),
    ('dragon_quest_viii', 'Square Enix', 'publisher', 'SLUS-21207'),
    ('drakan_the_ancients_gates', 'Surreal Software, Inc', 'developer', 'SCUS-97128'),
    ('drakan_the_ancients_gates', 'Sony Computer Entertainment', 'publisher', 'SCUS-97128'),
    ('drakengard', 'Cavia Inc', 'developer', 'SLUS-20732'),
    ('drakengard', 'Square Enix', 'publisher', 'SLUS-20732'),
    ('dreamworks_kung_fu_panda', 'XPEC Entertainment Inc', 'developer', 'SLUS-21757'),
    ('dreamworks_kung_fu_panda', 'Activision', 'publisher', 'SLUS-21757'),
    ('dreamworks_madagascar', 'Toys for Bob', 'developer', 'SLUS-21015'),
    ('dreamworks_madagascar', 'Activision', 'publisher', 'SLUS-21015'),
    ('dreamworks_shrek_smash_n_crash_racing', 'Torus Games Pty. Ltd', 'developer', 'SLUS-21392'),
    ('dreamworks_shrek_smash_n_crash_racing', 'Activision', 'publisher', 'SLUS-21392'),
    ('dreamworks_shrek_the_third', 'Amaze Entertainment', 'developer', 'SLUS-21454'),
    ('dreamworks_shrek_the_third', 'Activision', 'publisher', 'SLUS-21454'),
    ('driving_emotion_type_s', 'Escape', 'developer', 'SLUS-20113'),
    ('driving_emotion_type_s', 'Squaresoft', 'publisher', 'SLUS-20113'),
    ('dual_hearts', 'Matrix', 'developer', 'SLUS-20475'),
    ('dual_hearts', 'Atlus U.S.A', 'publisher', 'SLUS-20475'),
    ('dynasty_warriors_2', 'Omega Force', 'developer', 'SLUS-20079'),
    ('dynasty_warriors_2', 'Koei', 'publisher', 'SLUS-20079'),
    ('dynasty_warriors_3', 'Omega Force', 'developer', 'SLUS-20277'),
    ('dynasty_warriors_3', 'Koei', 'publisher', 'SLUS-20277'),
    ('eagle_eye_golf', 'Telenet Japan', 'developer', 'SLUS-21486'),
    ('eagle_eye_golf', 'Aksys Games', 'publisher', 'SLUS-21486'),
    ('ecco_the_dolphin_defender_of_the_future', 'Appaloosa Interactive', 'developer', 'SLUS-20394'),
    ('ecco_the_dolphin_defender_of_the_future', 'Acclaim Entertainment, Inc', 'publisher', 'SLUS-20394'),
    ('echo_night_beyond', 'From Software, Inc', 'developer', 'SLUS-20928'),
    ('echo_night_beyond', 'Agetec, Inc', 'publisher', 'SLUS-20928'),
    ('endgame', 'Cunning Developments', 'developer', 'SLUS-20389'),
    ('endgame', 'Empire Interactive, Inc', 'publisher', 'SLUS-20389'),
    ('enthusia_professional_racing', 'Konami', 'developer', 'SLUS-20967'),
    ('enthusia_professional_racing', 'Konami', 'publisher', 'SLUS-20967'),
    ('ephemeral_fantasia', 'KCEJ', 'developer', 'SLUS-20169'),
    ('ephemeral_fantasia', 'Konami', 'publisher', 'SLUS-20169'),
    ('eragon', 'Stormfront Studios', 'developer', 'SLUS-21322'),
    ('eragon', 'Sierra Entertainment', 'publisher', 'SLUS-21322'),
    ('escape_from_monkey_island', 'Lucasarts', 'developer', 'SLUS-20181'),
    ('escape_from_monkey_island', 'Lucasarts', 'publisher', 'SLUS-20181'),
    ('espn_international_track_field', 'Konami', 'developer', 'SLUS-20041'),
    ('espn_international_track_field', 'Konami', 'publisher', 'SLUS-20041'),
    ('espn_international_winter_sports_2002', 'Konami Computer Entertainment Osaka (KCEO)', 'developer', 'SLUS-20320'),
    ('espn_international_winter_sports_2002', 'Konami', 'publisher', 'SLUS-20320'),
    ('eternal_poison', 'Flight-Plan', 'developer', 'SLUS-21779'),
    ('eternal_poison', 'Atlus / Bandai Namco Games', 'publisher', 'SLUS-21779'),
    ('eureka_seven_vol_1_the_new_wave', 'Bandai Entertainment Company', 'developer', 'SLUS-21353'),
    ('eureka_seven_vol_1_the_new_wave', 'Namco Bandai Games America, Inc', 'publisher', 'SLUS-21353'),
    ('evergrace', 'From Software', 'developer', 'SLUS-20016'),
    ('evergrace', 'Agetec', 'publisher', 'SLUS-20016'),
    ('evil_dead_a_fistful_of_boomstick', 'VIS entertainment plc', 'developer', 'SLUS-20403'),
    ('evil_dead_a_fistful_of_boomstick', 'THQ', 'publisher', 'SLUS-20403'),
    ('evil_dead_regeneration', 'Cranky Pants Games', 'developer', 'SLUS-21048'),
    ('evil_dead_regeneration', 'THQ', 'publisher', 'SLUS-21048'),
    ('fallout_brotherhood_of_steel', 'Interplay Entertainment Corp', 'developer', 'SLUS-20539'),
    ('fallout_brotherhood_of_steel', 'Interplay Entertainment Corp', 'publisher', 'SLUS-20539'),
    ('fantastic_4', '7 Studios', 'developer', 'SLUS-20615'),
    ('fantastic_4', 'Activision', 'publisher', 'SLUS-20615'),
    ('fantastic_four_rise_of_the_silver_surfer', '7 Studios Inc', 'developer', 'SLUS-21544'),
    ('fantastic_four_rise_of_the_silver_surfer', '2K Games', 'publisher', 'SLUS-21544'),
    ('fatal_frame', 'Tecmo', 'developer', 'SLUS-20388'),
    ('fatal_frame', 'Tecmo', 'publisher', 'SLUS-20388'),
    ('fatal_frame_ii_crimson_butterfly', 'Tecmo', 'developer', 'SLUS-20766'),
    ('fatal_frame_ii_crimson_butterfly', 'Tecmo', 'publisher', 'SLUS-20766'),
    ('fatal_frame_iii_the_tormented', 'Tecmo', 'developer', 'SLUS-21244'),
    ('fatal_frame_iii_the_tormented', 'Tecmo', 'publisher', 'SLUS-21244'),
    ('ferrari_f355_challenge', 'AM2 / Tose Co., Ltd', 'developer', 'SLUS-20558'),
    ('ferrari_f355_challenge', 'Sega', 'publisher', 'SLUS-20558'),
    ('fifa_soccer_12', 'EA Canada', 'developer', 'SLUS-21947'),
    ('fifa_soccer_12', 'Electronic Arts', 'publisher', 'SLUS-21947'),
    ('fight_club', 'Genuine Games', 'developer', 'SLUS-20857'),
    ('fight_club', 'Vivendi Universal Games', 'publisher', 'SLUS-20857'),
    ('fight_night_round_3', 'EA Chicago', 'developer', 'SLUS-21383'),
    ('fight_night_round_3', 'Electronic Arts', 'publisher', 'SLUS-21383'),
    ('final_fantasy_x', 'Square Co. Ltd', 'developer', 'SLUS-20312'),
    ('final_fantasy_x', 'Square Enix', 'publisher', 'SLUS-20312'),
    ('final_fantasy_x_2', 'Square Enix', 'developer', 'SLUS-20672'),
    ('final_fantasy_x_2', 'Square Enix', 'publisher', 'SLUS-20672'),
    ('final_fantasy_xii', 'S-Force', 'developer', 'SLUS-20963'),
    ('final_fantasy_xii', 'Square Enix', 'publisher', 'SLUS-20963'),
    ('final_fight_streetwise', 'Capcom', 'developer', 'SLUS-21238'),
    ('final_fight_streetwise', 'Capcom', 'publisher', 'SLUS-21238'),
    ('finny_the_fish_the_seven_waters', 'Overworks', 'developer', 'SLUS-21072'),
    ('finny_the_fish_the_seven_waters', 'Natsume / Sega', 'publisher', 'SLUS-21072'),
    ('firefighter_f_d_18', 'Konami', 'developer', 'SLUS-20724'),
    ('firefighter_f_d_18', 'Konami', 'publisher', 'SLUS-20724'),
    ('flatout', 'Bugbear Entertainment Ltd', 'developer', 'SLUS-20901'),
    ('flatout', 'Empire Interactive', 'publisher', 'SLUS-20901'),
    ('flatout_2_2006_1', 'Bugbear Entertainment Ltd', 'developer', 'SLUS-21251'),
    ('flatout_2_2006_1', 'Vivendi Games', 'publisher', 'SLUS-21251'),
    ('flipnic_ultimate_pinball', 'Sony', 'developer', 'SLUS-21157'),
    ('flipnic_ultimate_pinball', 'Capcom', 'publisher', 'SLUS-21157'),
    ('flow_urban_dance_uprising', 'Artificial Mind and Movement (A2M)', 'developer', 'SLUS-21319'),
    ('flow_urban_dance_uprising', 'Ubisoft Entertainment', 'publisher', 'SLUS-21319'),
    ('ford_racing_2', 'Razorworks', 'developer', 'SLUS-20788'),
    ('ford_racing_2', 'Gotham Games', 'publisher', 'SLUS-20788'),
    ('forgotten_realms_demon_stone', 'Stormfront Studios', 'developer', 'SLUS-20804'),
    ('forgotten_realms_demon_stone', 'Atari, Inc', 'publisher', 'SLUS-20804'),
    ('freedom_fighters', 'IO Interactive', 'developer', 'SLUS-20658'),
    ('freedom_fighters', 'Electronic Arts', 'publisher', 'SLUS-20658'),
    ('freekstyle', 'Page 44 Studios', 'developer', 'SLUS-20367'),
    ('freekstyle', 'Electronic Arts', 'publisher', 'SLUS-20367'),
    ('frogger_ancient_shadow', 'Hudson Soft Co., Ltd', 'developer', 'SLUS-21098'),
    ('frogger_ancient_shadow', 'Konami', 'publisher', 'SLUS-21098'),
    ('frogger_the_great_quest', 'Konami', 'developer', 'SLUS-20257'),
    ('frogger_the_great_quest', 'Konami', 'publisher', 'SLUS-20257'),
    ('front_mission_4', 'Square Enix', 'developer', 'SLUS-20888'),
    ('front_mission_4', 'Square Enix', 'publisher', 'SLUS-20888'),
    ('full_spectrum_warrior', 'Pandemic Studio Pty. Ltd', 'developer', 'SLUS-21145'),
    ('full_spectrum_warrior', 'THQ', 'publisher', 'SLUS-21145'),
    ('fullmetal_alchemist_and_the_broken_angel', 'Racjin', 'developer', 'SLUS-20994'),
    ('fullmetal_alchemist_and_the_broken_angel', 'Square Enix USA', 'publisher', 'SLUS-20994'),
    ('fullmetal_alchemist_2_curse_of_the_crimson_elixir', 'Racjin', 'developer', 'SLUS-21166'),
    ('fullmetal_alchemist_2_curse_of_the_crimson_elixir', 'Square Enix', 'publisher', 'SLUS-21166'),
    ('fur_fighters_viggo_s_revenge', 'Bizarre Creations', 'developer', 'SLUS-20088'),
    ('fur_fighters_viggo_s_revenge', 'Acclaim Entertainment, Inc', 'publisher', 'SLUS-20088'),
    ('futurama', 'Unique Development Studios (UDS)', 'developer', 'SLUS-20439'),
    ('futurama', 'Vivendi Universal Games', 'publisher', 'SLUS-20439'),
    ('g_i_joe_the_rise_of_cobra', 'Double Helix', 'developer', 'SLUS-21886'),
    ('g_i_joe_the_rise_of_cobra', 'Electronic Arts', 'publisher', 'SLUS-21886'),
    ('g1_jockey_3', 'Koei Co. Ltd', 'developer', 'SLUS-20690'),
    ('g1_jockey_3', 'Koei', 'publisher', 'SLUS-20690'),
    ('galactic_wrestling_featuring_ultimate_muscle', 'AKI Corporation', 'developer', 'SLUS-20822'),
    ('galactic_wrestling_featuring_ultimate_muscle', 'Bandai', 'publisher', 'SLUS-20822'),
    ('galerians_ash', 'Enterbrain, Inc', 'developer', 'SLUS-20560'),
    ('galerians_ash', 'Sammy Entertaiment', 'publisher', 'SLUS-20560'),
    ('gallop_racer_2001', 'Tecmo', 'developer', 'SLUS-20255'),
    ('gallop_racer_2001', 'Tecmo', 'publisher', 'SLUS-20255'),
    ('garfield_lasagna_world_tour', 'Eko Software', 'developer', 'SLUS-21749'),
    ('garfield_lasagna_world_tour', 'Conspiracy Entertainment', 'publisher', 'SLUS-21749'),
    ('gauntlet_dark_legacy', 'Midway', 'developer', 'SLUS-20047'),
    ('gauntlet_dark_legacy', 'Midway', 'publisher', 'SLUS-20047'),
    ('gauntlet_seven_sorrows', 'Midway', 'developer', 'SLUS-21077'),
    ('gauntlet_seven_sorrows', 'Midway', 'publisher', 'SLUS-21077'),
    ('genji_dawn_of_the_samurai', 'Game Republic', 'developer', 'SCUS-97471'),
    ('genji_dawn_of_the_samurai', 'Sony', 'publisher', 'SCUS-97471'),
    ('ghost_in_the_shell_stand_alone_complex', 'Cavia', 'developer', 'SLUS-21006'),
    ('ghost_in_the_shell_stand_alone_complex', 'Bandai', 'publisher', 'SLUS-21006'),
    ('ghost_rider', 'Climax Group', 'developer', 'SLUS-21306'),
    ('ghost_rider', '2K Games', 'publisher', 'SLUS-21306'),
    ('ghostbusters_the_video_game', 'Red Fly Studio', 'developer', 'SLUS-21882'),
    ('ghostbusters_the_video_game', 'Atari', 'publisher', 'SLUS-21882'),
    ('ghosthunter', 'SCE Studio Cambridge', 'developer', 'SLUS-20993'),
    ('ghosthunter', 'Namco', 'publisher', 'SLUS-20993'),
    ('gitaroo_man', 'Koei', 'developer', 'SLUS-20294'),
    ('gitaroo_man', 'Koei', 'publisher', 'SLUS-20294'),
    ('gladius', 'Lucasarts', 'developer', 'SLUS-20490'),
    ('gladius', 'Lucasarts', 'publisher', 'SLUS-20490'),
    ('god_hand', 'Clover Studio', 'developer', 'SLUS-21503'),
    ('god_hand', 'Capcom', 'publisher', 'SLUS-21503'),
    ('god_of_war_ii', 'Sony', 'developer', 'SCUS-97481'),
    ('god_of_war_ii', 'Sony', 'publisher', 'SCUS-97481'),
    ('godzilla_save_the_earth', 'Pipeworks Software, Inc', 'developer', 'SLUS-20809'),
    ('godzilla_save_the_earth', 'Atari', 'publisher', 'SLUS-20809'),
    ('gradius_iii_and_iv', 'Konami', 'developer', 'SLUS-20040'),
    ('gradius_iii_and_iv', 'Konami', 'publisher', 'SLUS-20040'),
    ('gradius_v', 'Treasure', 'developer', 'SLUS-20712'),
    ('gradius_v', 'Konami', 'publisher', 'SLUS-20712'),
    ('graffiti_kingdom', 'Taito Corporation', 'developer', 'SLUS-21136'),
    ('graffiti_kingdom', 'Hot-B USA', 'publisher', 'SLUS-21136'),
    ('gran_turismo_3_a_spec', 'Polyphony Digital', 'developer', 'SCUS-97102'),
    ('gran_turismo_3_a_spec', 'Sony', 'publisher', 'SCUS-97102'),
    ('grand_theft_auto_iii', 'DMA Design Ltd', 'developer', 'SLUS-20062'),
    ('grand_theft_auto_iii', 'Rockstar Games', 'publisher', 'SLUS-20062'),
    ('grand_theft_auto_vice_city', 'Rockstar North', 'developer', 'SLUS-20552'),
    ('grand_theft_auto_vice_city', 'Rockstar Games', 'publisher', 'SLUS-20552'),
    ('grand_theft_auto_vice_city_stories', 'Rockstar Leeds', 'developer', 'SLUS-21590'),
    ('grand_theft_auto_vice_city_stories', 'Rockstar Games', 'publisher', 'SLUS-21590'),
    ('grandia_ii', 'Gamearts', 'developer', 'SLUS-20194'),
    ('grandia_ii', 'Ubisoft', 'publisher', 'SLUS-20194'),
    ('grandia_iii', 'Game Arts', 'developer', 'SLUS-21334SLUS-21345'),
    ('grandia_iii', 'Square Enix USA', 'publisher', 'SLUS-21334SLUS-21345'),
    ('grandia_xtreme', 'Game Arts', 'developer', 'SLUS-20417'),
    ('grandia_xtreme', 'Enix', 'publisher', 'SLUS-20417'),
    ('gravity_games_bike_street_vert_dirt', 'Midway', 'developer', 'SLUS-20310'),
    ('gravity_games_bike_street_vert_dirt', 'Midway', 'publisher', 'SLUS-20310'),
    ('guilty_gear_x', 'Arc System Works', 'developer', 'SLUS-20287'),
    ('guilty_gear_x', 'Sammy Studios', 'publisher', 'SLUS-20287'),
    ('guilty_gear_x2', 'Arc System Works Co. Ltd', 'developer', 'SLUS-20436'),
    ('guilty_gear_x2', 'Sammy Studios, Inc', 'publisher', 'SLUS-20436'),
    ('guitar_hero', 'Harmonix Music Systems', 'developer', 'SLUS-21224'),
    ('guitar_hero', 'RedOctane', 'publisher', 'SLUS-21224'),
    ('guitar_hero_aerosmith', 'BudCat', 'developer', 'SLUS-21740'),
    ('guitar_hero_aerosmith', 'Activision', 'publisher', 'SLUS-21740'),
    ('gun', 'Neversoft', 'developer', 'SLUS-21139'),
    ('gun', 'Activision', 'publisher', 'SLUS-21139'),
    ('gungrave', 'Positron Co., Ltd', 'developer', 'SLUS-20493'),
    ('gungrave', 'Sega', 'publisher', 'SLUS-20493'),
    ('half_life', 'Gearbox Software / Valve L.L.C', 'developer', 'SLUS-20066'),
    ('half_life', 'Sierra On-Line, Inc', 'publisher', 'SLUS-20066'),
    ('hannspree_ten_kate_honda_sbk', 'Milestone S.r.l', 'developer', 'SLUS-21656'),
    ('hannspree_ten_kate_honda_sbk', 'Valcon Games', 'publisher', 'SLUS-21656'),
    ('happy_feet', 'A2M (Artificial Mind & Movement)', 'developer', 'SLUS-21455'),
    ('happy_feet', 'Midway Home Entertainment, Inc. / Warner Bros. Interactive Entertainment', 'publisher', 'SLUS-21455'),
    ('hard_hitter_tennis', 'Magical Company', 'developer', 'SLUS-20568'),
    ('hard_hitter_tennis', 'Atlus U.S.A., Inc', 'publisher', 'SLUS-20568'),
    ('harry_potter_and_the_goblet_of_fire', 'Electronic Arts', 'developer', 'SLUS-21325'),
    ('harry_potter_and_the_goblet_of_fire', 'Electronic Arts', 'publisher', 'SLUS-21325'),
    ('harry_potter_and_the_order_of_the_phoenix', 'Electronic Arts Chertsey', 'developer', 'SLUS-21619'),
    ('harry_potter_and_the_order_of_the_phoenix', 'Electronic Arts', 'publisher', 'SLUS-21619'),
    ('harvest_moon_a_wonderful_life_special_edition', 'Tose', 'developer', 'SLUS-21171'),
    ('harvest_moon_a_wonderful_life_special_edition', 'Natsume', 'publisher', 'SLUS-21171'),
    ('harvest_moon_save_the_homeland', 'Marucome', 'developer', 'SLUS-20251'),
    ('harvest_moon_save_the_homeland', 'Natsume Inc', 'publisher', 'SLUS-20251'),
    ('harvey_birdman_attorney_at_law', 'High Voltage Software', 'developer', 'SLUS-21680'),
    ('harvey_birdman_attorney_at_law', 'Capcom', 'publisher', 'SLUS-21680'),
    ('haunting_ground', 'Capcom Production Studio 1', 'developer', 'SLUS-21075'),
    ('haunting_ground', 'Capcom', 'publisher', 'SLUS-21075'),
    ('haven_call_of_the_king', 'Traveller''s Tales', 'developer', 'SLUS-20517'),
    ('haven_call_of_the_king', 'Midway Home Entertainment', 'publisher', 'SLUS-20517'),
    ('headhunter', 'Amuze', 'developer', 'SLUS-20416'),
    ('headhunter', 'Acclaim Entertainment, Inc', 'publisher', 'SLUS-20416'),
    ('headhunter_redemption', 'Amusement Vision', 'developer', 'SLUS-20817'),
    ('headhunter_redemption', 'Sega', 'publisher', 'SLUS-20817'),
    ('heatseeker', 'IR Gurus', 'developer', 'SLUS-21570'),
    ('heatseeker', 'Codemasters', 'publisher', 'SLUS-21570'),
    ('heavenly_guardian', 'Starfish', 'developer', 'SLUS-21653'),
    ('heavenly_guardian', 'UFO Interactive', 'publisher', 'SLUS-21653'),
    ('herdy_gerdy', 'Core Design Ltd', 'developer', 'SLUS-20231'),
    ('herdy_gerdy', 'Eidos Interactive', 'publisher', 'SLUS-20231'),
    ('heroes_of_the_pacific', 'IR Gurus', 'developer', 'SLUS-20943'),
    ('heroes_of_the_pacific', 'Ubisoft', 'publisher', 'SLUS-20943'),
    ('hidden_invasion', 'Toka S.a.r.l', 'developer', 'SLUS-20301'),
    ('hidden_invasion', 'Conspiracy Entertainment Corporation', 'publisher', 'SLUS-20301'),
    ('hitman_blood_money', 'IO Interactive A/S', 'developer', 'SLUS-21108'),
    ('hitman_blood_money', 'Eidos Interactive', 'publisher', 'SLUS-21108'),
    ('hot_shots_golf_fore', 'Clap Hanz', 'developer', 'SCUS-97401'),
    ('hot_shots_golf_fore', 'Sony', 'publisher', 'SCUS-97401'),
    ('hot_shots_tennis', 'Clap Hanz', 'developer', 'SCUS-97610'),
    ('hot_shots_tennis', 'Sony', 'publisher', 'SCUS-97610'),
    ('hot_wheels_stunt_track_challenge', 'Climax Group', 'developer', 'SLUS-20954'),
    ('hot_wheels_stunt_track_challenge', 'THQ', 'publisher', 'SLUS-20954'),
    ('hunter_the_reckoning_wayward', 'High Voltage Software, Inc', 'developer', 'SLUS-20511'),
    ('hunter_the_reckoning_wayward', 'Vivendi Universal Games', 'publisher', 'SLUS-20511'),
    ('i_ninja', 'Argonaut Software Ltd', 'developer', 'SLUS-20705'),
    ('i_ninja', 'Namco', 'publisher', 'SLUS-20705'),
    ('ice_age_2_the_meltdown', 'Eurocom Entertainment Software', 'developer', 'SLUS-21307'),
    ('ice_age_2_the_meltdown', 'Sierra Entertainment', 'publisher', 'SLUS-21307'),
    ('ico', 'Sony Computer Entertaiment', 'developer', 'SCUS-97113'),
    ('ico', 'Sony Computer Entertaiment', 'publisher', 'SCUS-97113'),
    ('indigo_prophecy', 'Quantic Dreams', 'developer', 'SLUS-21196'),
    ('indigo_prophecy', 'Atari', 'publisher', 'SLUS-21196'),
    ('inuyasha_feudal_combat', 'Eighting Co., Ltd. (8ing)', 'developer', 'SLUS-21193'),
    ('inuyasha_feudal_combat', 'Bandai', 'publisher', 'SLUS-21193'),
    ('inuyasha_the_secret_of_the_cursed_mask', 'Kamui', 'developer', 'SLUS-20913'),
    ('inuyasha_the_secret_of_the_cursed_mask', 'Bandai', 'publisher', 'SLUS-20913'),
    ('iron_man', 'Artificial Mind and Movement (A2M)', 'developer', 'SLUS-21739'),
    ('iron_man', 'Sega', 'publisher', 'SLUS-21739'),
    ('jade_cocoon_2', 'Genki Co', 'developer', 'SLUS-20309'),
    ('jade_cocoon_2', 'Ubisoft Entertainment', 'publisher', 'SLUS-20309'),
    ('jak_ii', 'Naughty Dog', 'developer', 'SCUS-97265'),
    ('jak_ii', 'Sony', 'publisher', 'SCUS-97265'),
    ('jak_x_combat_racing', 'Naughty Dog', 'developer', 'SCUS-97429'),
    ('jak_x_combat_racing', 'Sony', 'publisher', 'SCUS-97429'),
    ('james_cameron_s_dark_angel', 'Radical Entertainment Inc', 'developer', 'SLUS-20379'),
    ('james_cameron_s_dark_angel', 'Sierra Entertainment, Inc', 'publisher', 'SLUS-20379'),
    ('jaws_unleashed', 'Appaloosa Interactive', 'developer', 'SLUS-21062'),
    ('jaws_unleashed', 'Majesco Entertainment', 'publisher', 'SLUS-21062'),
    ('jeremy_mcgrath_supercross_world', 'Acclaim Studios Salt Lake City, Inc', 'developer', 'SLUS-20245'),
    ('jeremy_mcgrath_supercross_world', 'Acclaim', 'publisher', 'SLUS-20245'),
    ('jet_li_rise_to_honor', 'Sony', 'developer', 'SCUS-97279'),
    ('jet_li_rise_to_honor', 'Sony', 'publisher', 'SCUS-97279'),
    ('judge_dredd_dredd_vs_death', 'Rebellion Developments Ltd', 'developer', 'SLUS-20869'),
    ('judge_dredd_dredd_vs_death', 'BAM! Entertainment, Inc', 'publisher', 'SLUS-20869'),
    ('juiced', 'Juice Games, Ltd', 'developer', 'SLUS-20872'),
    ('juiced', 'THQ', 'publisher', 'SLUS-20872'),
    ('jumper_griffin_s_story', 'Collision Studios', 'developer', 'SLUS-21730'),
    ('jumper_griffin_s_story', 'Brash Entertainment, LLC', 'publisher', 'SLUS-21730'),
    ('jurassic_park_operation_genesis', 'Blue Tongue Entertainment Limited', 'developer', 'SLUS-20380'),
    ('jurassic_park_operation_genesis', 'Konami', 'publisher', 'SLUS-20380'),
    ('just_cause', 'Avalanche Software', 'developer', 'SLUS-21436'),
    ('just_cause', 'Eidos Interactive', 'publisher', 'SLUS-21436'),
    ('justice_league_heroes', 'Snowblind Studios', 'developer', 'SLUS-21304'),
    ('justice_league_heroes', 'Warner Bros. Interactive Entertainment', 'publisher', 'SLUS-21304'),
    ('kao_the_kangaroo_round_2', 'Tate Interactive Sp z.o.o', 'developer', 'SLUS-20296'),
    ('kao_the_kangaroo_round_2', 'Atari', 'publisher', 'SLUS-20296'),
    ('kelly_slater_s_pro_surfer', 'Treyarch', 'developer', 'SLUS-20334'),
    ('kelly_slater_s_pro_surfer', 'Activision', 'publisher', 'SLUS-20334'),
    ('kengo_master_of_bushido', 'LightWeight Co., Ltd', 'developer', 'SLUS-20021'),
    ('kengo_master_of_bushido', 'Crave Entertainment, Inc', 'publisher', 'SLUS-20021'),
    ('kessen', 'Koei', 'developer', 'SLUS-20098'),
    ('kessen', 'Koei / Electronic Arts', 'publisher', 'SLUS-20098'),
    ('kill_switch', 'Namco Hometek, Inc', 'developer', 'SLUS-20706'),
    ('kill_switch', 'Namco', 'publisher', 'SLUS-20706'),
    ('killzone', 'Guerrilla', 'developer', 'SCUS-97402'),
    ('killzone', 'Sony', 'publisher', 'SCUS-97402'),
    ('kinetica', 'SCE Santa Monica Studio', 'developer', 'SCUS-97132'),
    ('kinetica', 'Sony Computer Entertainment America, Inc', 'publisher', 'SCUS-97132'),
    ('king_arthur', 'Krome Studios', 'developer', 'SLUS-21046'),
    ('king_arthur', 'Konami', 'publisher', 'SLUS-21046'),
    ('kingdom_hearts', 'Square Enix', 'developer', 'SLUS-20370'),
    ('kingdom_hearts', 'Square Co. Ltd', 'publisher', 'SLUS-20370'),
    ('kingdom_hearts_re_chain_of_memories', 'Jupiter Corporation', 'developer', 'SLUS-21799'),
    ('kingdom_hearts_re_chain_of_memories', 'Square Enix', 'publisher', 'SLUS-21799'),
    ('klonoa_2_lunatea_s_veil', 'Namco', 'developer', 'SLUS-20151'),
    ('klonoa_2_lunatea_s_veil', 'Namco', 'publisher', 'SLUS-20151'),
    ('kuon', 'FromSoftware, Inc', 'developer', 'SLUS-21007'),
    ('kuon', 'Agetec Inc', 'publisher', 'SLUS-21007'),
    ('kya_dark_lineage', 'Eden Studios', 'developer', 'SLUS-20440'),
    ('kya_dark_lineage', 'Atari', 'publisher', 'SLUS-20440'),
    ('l_a_rush', 'Pitbull Syndicate', 'developer', 'SLUS-21112'),
    ('l_a_rush', 'Midway Home Entertainment', 'publisher', 'SLUS-21112'),
    ('le_mans_24_hours', 'Torus Games', 'developer', 'SLUS-20207'),
    ('le_mans_24_hours', 'Infogrames', 'publisher', 'SLUS-20207'),
    ('legacy_of_kain_blood_omen_2', 'Crystal Dynamics, Inc', 'developer', 'SLUS-20024'),
    ('legacy_of_kain_blood_omen_2', 'Eidos Interactive', 'publisher', 'SLUS-20024'),
    ('legaia_2_duel_saga', 'Prokion', 'developer', 'SLUS-20414'),
    ('legaia_2_duel_saga', 'Fresh Games / Eidos Interactive', 'publisher', 'SLUS-20414'),
    ('legend_of_kay', 'NEON Software GmbH', 'developer', 'SLUS-21248'),
    ('legend_of_kay', 'Capcom', 'publisher', 'SLUS-21248'),
    ('legend_of_the_dragon', 'Neko Entertainment', 'developer', 'SLUS-21612'),
    ('legend_of_the_dragon', 'The Game Factory', 'publisher', 'SLUS-21612'),
    ('legion_the_legend_of_excalibur', '7 Studios', 'developer', 'SLUS-20048'),
    ('legion_the_legend_of_excalibur', 'Midway', 'publisher', 'SLUS-20048'),
    ('lego_batman_the_videogame', 'Traveller''s Tales', 'developer', 'SLUS-21785'),
    ('lego_batman_the_videogame', 'Warner Interactive', 'publisher', 'SLUS-21785'),
    ('lego_indiana_jones_the_original_adventures', 'Traveller''s Tales', 'developer', 'SLUS-21759'),
    ('lego_indiana_jones_the_original_adventures', 'Lucasarts', 'publisher', 'SLUS-21759'),
    ('lego_racers_2', 'Attention to Detail Limited', 'developer', 'SLUS-20042'),
    ('lego_racers_2', 'Electronics Arts / LEGO Software', 'publisher', 'SLUS-20042'),
    ('lego_star_wars_ii_the_original_trilogy', 'Traveller''s Tales', 'developer', 'SLUS-21409'),
    ('lego_star_wars_ii_the_original_trilogy', 'Lucasarts', 'publisher', 'SLUS-21409'),
    ('leisure_suit_larry_magna_cum_laude', 'High Voltage Software, Inc', 'developer', 'SLUS-20956'),
    ('leisure_suit_larry_magna_cum_laude', 'Sierra Entertainment', 'publisher', 'SLUS-20956'),
    ('lemony_snicket_s_a_series_of_unfortunate_events', 'Adrenium Games', 'developer', 'SLUS-21078'),
    ('lemony_snicket_s_a_series_of_unfortunate_events', 'Activision', 'publisher', 'SLUS-21078'),
    ('let_s_ride_silver_buckle_stables', 'Coresoft, Inc', 'developer', 'SLUS-21309'),
    ('let_s_ride_silver_buckle_stables', 'ValuSoft, Inc', 'publisher', 'SLUS-21309'),
    ('looney_tunes_acme_arsenal', 'Redtribe', 'developer', 'SLUS-21636'),
    ('looney_tunes_acme_arsenal', 'Warner Bros. Interactive Entertainment', 'publisher', 'SLUS-21636'),
    ('looney_tunes_back_in_action', 'Warthog', 'developer', 'SLUS-20853'),
    ('looney_tunes_back_in_action', 'Electronic Arts', 'publisher', 'SLUS-20853'),
    ('looney_tunes_space_race', 'Tantalus Interactive', 'developer', 'SLUS-20352'),
    ('looney_tunes_space_race', 'Infogrames', 'publisher', 'SLUS-20352'),
    ('lupin_the_3rd_treasure_of_the_sorcerer_king', 'Banpresto', 'developer', 'SLUS-20683'),
    ('lupin_the_3rd_treasure_of_the_sorcerer_king', 'Bandai', 'publisher', 'SLUS-20683'),
    ('mace_griffin_bounty_hunter', 'Warthog Games Ltd', 'developer', 'SLUS-20505'),
    ('mace_griffin_bounty_hunter', 'Black Label Games', 'publisher', 'SLUS-20505'),
    ('mad_maestro', 'Desert Productions, Inc.', 'developer', 'SLUS-20376'),
    ('mad_maestro', 'Eidos Interactive', 'publisher', 'SLUS-20376'),
    ('madden_nfl_08', 'EA Tiburon', 'developer', 'SLUS-21638'),
    ('madden_nfl_08', 'EA Sports', 'publisher', 'SLUS-21638'),
    ('madden_nfl_08', 'EA Tiburon', 'developer', 'SLUS-21705'),
    ('madden_nfl_08', 'EA Sports', 'publisher', 'SLUS-21705'),
    ('made_man_confessions_of_the_family_blood', 'Silverback Studios', 'developer', 'SLUS-21587'),
    ('made_man_confessions_of_the_family_blood', 'Aspyr', 'publisher', 'SLUS-21587'),
    ('magic_pengel_the_quest_for_color', 'Taito / Garakuta-Studio', 'developer', 'SLUS-20593'),
    ('magic_pengel_the_quest_for_color', 'Agetec Inc', 'publisher', 'SLUS-20593'),
    ('magna_carta_tears_of_blood', 'Softmax Co. Ltd', 'developer', 'SLUS-21221'),
    ('magna_carta_tears_of_blood', 'Atlus', 'publisher', 'SLUS-21221'),
    ('makai_kingdom_chronicles_of_the_sacred_tome', 'Nippon Ichi Software', 'developer', 'SLUS-21170'),
    ('makai_kingdom_chronicles_of_the_sacred_tome', 'NIS America', 'publisher', 'SLUS-21170'),
    ('manhunt', 'Rockstar North', 'developer', 'SLUS-20827'),
    ('manhunt', 'Rockstar Games', 'publisher', 'SLUS-20827'),
    ('manhunt_2', 'Rockstar London', 'developer', 'SLUS-21613'),
    ('manhunt_2', 'Rockstar Games / Take 2', 'publisher', 'SLUS-21613'),
    ('marvel_super_hero_squad', 'Mass Media Inc', 'developer', 'SLUS-21910'),
    ('marvel_super_hero_squad', 'THQ', 'publisher', 'SLUS-21910'),
    ('marvel_ultimate_alliance', 'Raven Software', 'developer', 'SLUS-21374'),
    ('marvel_ultimate_alliance', 'Activision', 'publisher', 'SLUS-21374'),
    ('marvel_vs_capcom_2', 'Capcom Co., Ltd', 'developer', 'SLUS-20486'),
    ('marvel_vs_capcom_2', 'Capcom', 'publisher', 'SLUS-20486'),
    ('mat_hoffman_s_pro_bmx_2', 'Rainbow Studios', 'developer', 'SLUS-20335'),
    ('mat_hoffman_s_pro_bmx_2', 'Activision', 'publisher', 'SLUS-20335'),
    ('max_payne', 'Remedy Entertaiment', 'developer', 'SLUS-20230'),
    ('max_payne', 'Rockstar Games', 'publisher', 'SLUS-20230'),
    ('maximo_vs_army_of_zin', 'Capcom', 'developer', 'SLUS-20722'),
    ('maximo_vs_army_of_zin', 'Capcom', 'publisher', 'SLUS-20722'),
    ('mcfarlane_s_evil_prophecy', 'Konami', 'developer', 'SLUS-20657'),
    ('mcfarlane_s_evil_prophecy', 'Konami', 'publisher', 'SLUS-20657'),
    ('medal_of_honor_european_assault', 'EA Los Angeles', 'developer', 'SLUS-21199'),
    ('medal_of_honor_european_assault', 'Electronic Arts', 'publisher', 'SLUS-21199'),
    ('medal_of_honor_frontline', 'DreamWorks Interactive', 'developer', 'SLUS-20368'),
    ('medal_of_honor_frontline', 'Electronic Arts', 'publisher', 'SLUS-20368'),
    ('medal_of_honor_rising_sun', 'EA LA', 'developer', 'SLUS-20753'),
    ('medal_of_honor_rising_sun', 'Electronic Arts', 'publisher', 'SLUS-20753'),
    ('men_in_black_ii_alien_escape', 'Infogrames Melbourne House', 'developer', 'SLUS-20373'),
    ('men_in_black_ii_alien_escape', 'Infogrames', 'publisher', 'SLUS-20373'),
    ('mercenaries_playground_of_destruction', 'Pandemic Studio Pty. Ltd', 'developer', 'SLUS-20932'),
    ('mercenaries_playground_of_destruction', 'Lucasarts', 'publisher', 'SLUS-20932'),
    ('mercury_meltdown_remix', 'Ignition Entertainment', 'developer', 'SLUS-21548'),
    ('mercury_meltdown_remix', 'Ignition Entertainment', 'publisher', 'SLUS-21548'),
    ('metal_gear_solid_2_sons_of_liberty', 'Konami', 'developer', 'SLUS-20144'),
    ('metal_gear_solid_2_sons_of_liberty', 'Konami', 'publisher', 'SLUS-20144'),
    ('metal_gear_solid_3', 'Konami', 'developer', 'SLUS-20915'),
    ('metal_gear_solid_3', 'Konami', 'publisher', 'SLUS-20915'),
    ('metal_gear_solid_3_subsistence', 'Konami', 'developer', 'SLUS-21243SLUS-21359SLUS-21360'),
    ('metal_gear_solid_3_subsistence', 'Konami', 'publisher', 'SLUS-21243SLUS-21359SLUS-21360'),
    ('metal_saga', 'Crea-Tech', 'developer', 'SLUS-21293'),
    ('metal_saga', 'Atlus', 'publisher', 'SLUS-21293'),
    ('metal_slug_4_5', 'SNK Playmore', 'developer', 'SLUS-20971SLUS-20990'),
    ('metal_slug_4_5', 'SNK Playmore', 'publisher', 'SLUS-20971SLUS-20990'),
    ('metal_slug_anthology', 'SNK Playmore', 'developer', 'SLUS-21550'),
    ('metal_slug_anthology', 'SNK Playmore', 'publisher', 'SLUS-21550'),
    ('metropolismania', 'Indi Software Co., Ltd', 'developer', 'SLUS-20377'),
    ('metropolismania', 'Natsume Inc', 'publisher', 'SLUS-20377'),
    ('micro_machines_v4', 'Supersonic Software Ltd', 'developer', 'SLUS-21402'),
    ('micro_machines_v4', 'Codemasters', 'publisher', 'SLUS-21402'),
    ('midnight_club_street_racing', 'Angel Studios', 'developer', 'SLUS-20063'),
    ('midnight_club_street_racing', 'Rockstar Games', 'publisher', 'SLUS-20063'),
    ('midnight_club_ii', 'Rockstar San Diego', 'developer', 'SLUS-20209'),
    ('midnight_club_ii', 'Rockstar Games', 'publisher', 'SLUS-20209'),
    ('mission_impossible_operation_surma', 'Paradigm Entertainment, Inc', 'developer', 'SLUS-20400'),
    ('mission_impossible_operation_surma', 'Atari', 'publisher', 'SLUS-20400'),
    ('mobile_suit_gundam_journey_to_jaburo', 'Bandai', 'developer', 'SLUS-20175'),
    ('mobile_suit_gundam_journey_to_jaburo', 'Bandai', 'publisher', 'SLUS-20175'),
    ('monster_house', 'Artificial Mind and Movement (A2M)', 'developer', 'SLUS-21400'),
    ('monster_house', 'THQ', 'publisher', 'SLUS-21400'),
    ('monster_hunter', 'Capcom', 'developer', 'SLUS-20896'),
    ('monster_hunter', 'Capcom', 'publisher', 'SLUS-20896'),
    ('monster_rancher_3', 'Tecmo', 'developer', 'SLUS-20190'),
    ('monster_rancher_3', 'Tecmo', 'publisher', 'SLUS-20190'),
    ('mortal_kombat_armageddon', 'Midway', 'developer', 'SLUS-21410'),
    ('mortal_kombat_armageddon', 'Midway Home Entertainment, Inc', 'publisher', 'SLUS-21410'),
    ('mortal_kombat_deadly_alliance', 'Midway', 'developer', 'SLUS-20423'),
    ('mortal_kombat_deadly_alliance', 'Midway Home Entertainment, Inc', 'publisher', 'SLUS-20423'),
    ('mortal_kombat_deception', 'Midway Amusement Games, LLC', 'developer', 'SLUS-20881'),
    ('mortal_kombat_deception', 'Midway', 'publisher', 'SLUS-20881'),
    ('mortal_kombat_shaolin_monks', 'Midway', 'developer', 'SLUS-21087'),
    ('mortal_kombat_shaolin_monks', 'Midway', 'publisher', 'SLUS-21087'),
    ('motogp_3', 'Namco', 'developer', 'SLUS-20625'),
    ('motogp_3', 'Namco', 'publisher', 'SLUS-20625'),
    ('muppets_party_cruise', 'Mass Media Inc', 'developer', 'SLUS-20635'),
    ('muppets_party_cruise', 'TDK Mediactive', 'publisher', 'SLUS-20635'),
    ('mystic_heroes', 'Koei', 'developer', 'SLUS-20521'),
    ('mystic_heroes', 'Koei', 'publisher', 'SLUS-20521'),
    ('nano_breaker', 'Konami', 'developer', 'SLUS-21010'),
    ('nano_breaker', 'Konami', 'publisher', 'SLUS-21010'),
    ('narc', 'Point of View, Inc', 'developer', 'SLUS-20730'),
    ('narc', 'Midway', 'publisher', 'SLUS-20730'),
    ('naruto_ultimate_ninja', 'CyberConnect2', 'developer', 'SLUS-21358'),
    ('naruto_ultimate_ninja', 'Namco Bandai', 'publisher', 'SLUS-21358'),
    ('naruto_ultimate_ninja_2', 'CyberConnect2', 'developer', 'SLUS-21575'),
    ('naruto_ultimate_ninja_2', 'Namco Bandai', 'publisher', 'SLUS-21575'),
    ('naruto_uzumaki_chronicles', 'Cavia, Inc', 'developer', 'SLUS-21498'),
    ('naruto_uzumaki_chronicles', 'Namco Bandai', 'publisher', 'SLUS-21498'),
    ('nba_2k12', 'Virtuos', 'developer', 'SLUS-21950'),
    ('nba_2k12', '2K Games', 'publisher', 'SLUS-21950'),
    ('nba_street', 'NuFX, Inc', 'developer', 'SLUS-20187'),
    ('nba_street', 'EA Sports Big', 'publisher', 'SLUS-20187'),
    ('need_for_speed_carbon', 'Criterion Studios', 'developer', 'SLUS-21493'),
    ('need_for_speed_carbon', 'EA Games', 'publisher', 'SLUS-21493'),
    ('need_for_speed_hot_pursuit_2', 'DreamWorks Interactive', 'developer', 'SLUS-20362'),
    ('need_for_speed_hot_pursuit_2', 'Electronic Arts', 'publisher', 'SLUS-20362'),
    ('need_for_speed_underground', 'EA Black Box', 'developer', 'SLUS-20811'),
    ('need_for_speed_underground', 'Electronic Arts', 'publisher', 'SLUS-20811'),
    ('neo_contra', 'Konami Computer Entertainment Tokyo (KCET)', 'developer', 'SLUS-20961'),
    ('neo_contra', 'Konami', 'publisher', 'SLUS-20961'),
    ('neogeo_battle_coliseum', 'SNK Playmore Corporation', 'developer', 'SLUS-21708'),
    ('neogeo_battle_coliseum', 'SNK Playmore', 'publisher', 'SLUS-21708'),
    ('neopets_the_darkest_faerie', 'Idol Minds', 'developer', 'SCUS-97367'),
    ('neopets_the_darkest_faerie', 'Sony Computer Entertaiment America (SCEA)', 'publisher', 'SCUS-97367'),
    ('nicktoons_unite', 'Blue Tongue Entertainment Limited', 'developer', 'SLUS-21284'),
    ('nicktoons_unite', 'THQ', 'publisher', 'SLUS-21284'),
    ('ninja_assault', 'Now Production', 'developer', 'SLUS-20492'),
    ('ninja_assault', 'Namco', 'publisher', 'SLUS-20492'),
    ('obscure', 'Hydravision', 'developer', 'SLUS-20777'),
    ('obscure', 'DreamCatcher Interactive', 'publisher', 'SLUS-20777'),
    ('obscure_the_aftermath', 'Hydravision Entertainment', 'developer', 'SLUS-21709'),
    ('obscure_the_aftermath', 'Ignition Entertainment', 'publisher', 'SLUS-21709'),
    ('odin_sphere', 'Vanillaware, Ltd', 'developer', 'SLUS-21577'),
    ('odin_sphere', 'Atlus, Inc', 'publisher', 'SLUS-21577'),
    ('one_piece_grand_battle', 'Ganbarion Co. Ltd', 'developer', 'SLUS-20975'),
    ('one_piece_grand_battle', 'Bandai', 'publisher', 'SLUS-20975'),
    ('one_piece_pirates_carnival', 'H.A.N.D', 'developer', 'SLUS-21364'),
    ('one_piece_pirates_carnival', 'Namco Bandai Games America, Inc', 'publisher', 'SLUS-21364'),
    ('oni', 'Bunji', 'developer', 'SLUS-20064'),
    ('oni', 'Rockstar Games', 'publisher', 'SLUS-20064'),
    ('onimusha_blade_warriors', 'Capcom Production Studio 2', 'developer', 'SLUS-20710'),
    ('onimusha_blade_warriors', 'Capcom', 'publisher', 'SLUS-20710'),
    ('onimusha_warlords', 'Capcom', 'developer', 'SLUS-20018'),
    ('onimusha_warlords', 'Capcom', 'publisher', 'SLUS-20018'),
    ('onimusha_2_samurai_s_destiny', 'Capcom', 'developer', 'SLUS-20393'),
    ('onimusha_2_samurai_s_destiny', 'Capcom', 'publisher', 'SLUS-20393'),
    ('onimusha_3_demon_siege', 'Capcom', 'developer', 'SLUS-20694'),
    ('onimusha_3_demon_siege', 'Capcom', 'publisher', 'SLUS-20694'),
    ('open_season', 'Ubisoft Montreal', 'developer', 'SLUS-21467'),
    ('open_season', 'Ubisoft Entertainment', 'publisher', 'SLUS-21467'),
    ('orphen_scion_of_sorcery', 'Kadokawa', 'developer', 'SLUS-20011'),
    ('orphen_scion_of_sorcery', 'Activision', 'publisher', 'SLUS-20011'),
    ('outlaw_tennis', 'Hypnotix, Inc', 'developer', 'SLUS-21190'),
    ('outlaw_tennis', 'Global Star Software', 'publisher', 'SLUS-21190'),
    ('outrun_2006_coast_2_coast', 'Sumo Digital', 'developer', 'SLUS-21274'),
    ('outrun_2006_coast_2_coast', 'Sega', 'publisher', 'SLUS-21274'),
    ('pac_man_world_2', 'Namco', 'developer', 'SLUS-20224'),
    ('pac_man_world_2', 'Namco', 'publisher', 'SLUS-20224'),
    ('pac_man_world_3', 'Blitz Games', 'developer', 'SLUS-21219'),
    ('pac_man_world_3', 'Namco', 'publisher', 'SLUS-21219'),
    ('paris_dakar_rally', 'Broadsword Interactive', 'developer', 'SLUS-20324'),
    ('paris_dakar_rally', 'Acclaim', 'publisher', 'SLUS-20324'),
    ('peter_jackson_s_king_kong_the_official_game_of_the_movie', 'Ubisoft', 'developer', 'SLUS-21311'),
    ('peter_jackson_s_king_kong_the_official_game_of_the_movie', 'Ubisoft', 'publisher', 'SLUS-21311'),
    ('phantasy_star_universe', 'Sonic Team', 'developer', 'SLUS-21194'),
    ('phantasy_star_universe', 'Sega', 'publisher', 'SLUS-21194'),
    ('pinball_hall_of_fame_the_gottlieb_collection', 'Farsight Studios', 'developer', 'SLUS-21038'),
    ('pinball_hall_of_fame_the_gottlieb_collection', 'Crave', 'publisher', 'SLUS-21038'),
    ('pirates_legend_of_the_black_buccaneer', 'Widescreen Games', 'developer', 'SLUS-21478'),
    ('pirates_legend_of_the_black_buccaneer', 'Valcon Games, LLC', 'publisher', 'SLUS-21478'),
    ('pirates_the_legend_of_black_kat', 'Westwood Studios', 'developer', 'SLUS-20365'),
    ('pirates_the_legend_of_black_kat', 'Electronic Arts', 'publisher', 'SLUS-20365'),
    ('playboy_the_mansion', 'Cyberlore Studios', 'developer', 'SLUS-20988'),
    ('playboy_the_mansion', 'Arush Entertainment', 'publisher', 'SLUS-20988'),
    ('predator_concrete_jungle', 'Eurocom Entertainment Software', 'developer', 'SLUS-20875'),
    ('predator_concrete_jungle', 'Vivendi Universal Games', 'publisher', 'SLUS-20875'),
    ('prince_of_persia_the_sands_of_time', 'Ubisoft', 'developer', 'SLUS-20743'),
    ('prince_of_persia_the_sands_of_time', 'Ubisoft', 'publisher', 'SLUS-20743'),
    ('prince_of_persia_the_two_thrones', 'Ubisoft', 'developer', 'SLUS-21287'),
    ('prince_of_persia_the_two_thrones', 'Ubisoft', 'publisher', 'SLUS-21287'),
    ('pro_evolution_soccer_2012', 'Konami', 'developer', 'SLUS-21948'),
    ('pro_evolution_soccer_2012', 'Konami', 'publisher', 'SLUS-21948'),
    ('pro_evolution_soccer_2013', 'Konami', 'developer', 'SLUS-21955'),
    ('pro_evolution_soccer_2013', 'Konami', 'publisher', 'SLUS-21955'),
    ('project_snowblind', 'Crystal Dynamics, Inc', 'developer', 'SLUS-21037'),
    ('project_snowblind', 'Eidos, Inc', 'publisher', 'SLUS-21037'),
    ('pryzm_chapter_one_the_dark_unicorn', 'Digital Illusions', 'developer', 'SLUS-20172'),
    ('pryzm_chapter_one_the_dark_unicorn', 'TDK Mediactive', 'publisher', 'SLUS-20172'),
    ('psi_ops_the_mindgate_conspiracy', 'Midway Home Entertainment', 'developer', 'SLUS-20688'),
    ('psi_ops_the_mindgate_conspiracy', 'Midway Home Entertainment', 'publisher', 'SLUS-20688'),
    ('psychonauts', 'Budcat Creations', 'developer', 'SLUS-21120'),
    ('psychonauts', 'Majesco', 'publisher', 'SLUS-21120'),
    ('r_racing_evolution', 'Namco', 'developer', 'SLUS-20721'),
    ('r_racing_evolution', 'Namco', 'publisher', 'SLUS-20721'),
    ('r_type_final', 'Irem Software Engineering, Inc', 'developer', 'SLUS-20780'),
    ('r_type_final', 'Fresh Games', 'publisher', 'SLUS-20780'),
    ('radiata_stories', 'tri-Ace', 'developer', 'SLUS-21262'),
    ('radiata_stories', 'Square Enix', 'publisher', 'SLUS-21262'),
    ('rampage_total_destruction', 'Pipeworks Software, Inc', 'developer', 'SLUS-21323'),
    ('rampage_total_destruction', 'Midway', 'publisher', 'SLUS-21323'),
    ('ratchet_clank', 'Insomniac Games', 'developer', 'SCUS-97199'),
    ('ratchet_clank', 'Sony', 'publisher', 'SCUS-97199'),
    ('raw_danger', 'Irem', 'developer', 'SLUS-21501'),
    ('raw_danger', 'Agetec', 'publisher', 'SLUS-21501'),
    ('rayman_raving_rabbids', 'Ubisoft', 'developer', 'SLUS-21576'),
    ('rayman_raving_rabbids', 'Ubisoft', 'publisher', 'SLUS-21576'),
    ('rayman_3_hoodlum_havoc', 'Ubisoft', 'developer', 'SLUS-20601'),
    ('rayman_3_hoodlum_havoc', 'Ubisoft', 'publisher', 'SLUS-20601'),
    ('rc_revenge_pro', 'Acclaim', 'developer', 'SLUS-20153'),
    ('rc_revenge_pro', 'Acclaim', 'publisher', 'SLUS-20153'),
    ('rebel_raiders_operation_nighthawk', 'Kando Games SARL', 'developer', 'SLUS-21303'),
    ('rebel_raiders_operation_nighthawk', 'XS Games', 'publisher', 'SLUS-21303'),
    ('red_dead_revolver', 'Rockstar San Diego / Angel Studios', 'developer', 'SLUS-20500'),
    ('red_dead_revolver', 'Rockstar Games', 'publisher', 'SLUS-20500'),
    ('red_ninja_end_of_honor', 'Tranji', 'developer', 'SLUS-20714'),
    ('red_ninja_end_of_honor', 'Vivendi Universal Games, Inc', 'publisher', 'SLUS-20714'),
    ('reign_of_fire', 'Kuju Entertainment Ltd', 'developer', 'SLUS-20556'),
    ('reign_of_fire', 'BAM! Entertainment, Inc', 'publisher', 'SLUS-20556'),
    ('reservoir_dogs', 'Volatile Games', 'developer', 'SLUS-21479'),
    ('reservoir_dogs', 'Eidos Interactive', 'publisher', 'SLUS-21479'),
    ('resident_evil_code_veronica_x', 'Capcom', 'developer', 'SLUS-20184'),
    ('resident_evil_code_veronica_x', 'Capcom', 'publisher', 'SLUS-20184'),
    ('resident_evil_dead_aim', 'Cavia', 'developer', 'SLUS-20669'),
    ('resident_evil_dead_aim', 'Capcom', 'publisher', 'SLUS-20669'),
    ('resident_evil_outbreak', 'Capcom', 'developer', 'SLUS-20765'),
    ('resident_evil_outbreak', 'Capcom', 'publisher', 'SLUS-20765'),
    ('return_to_castle_wolfenstein_operation_resurrection', 'Gray Matter Interactive Studios, Inc', 'developer', 'SLUS-20297'),
    ('return_to_castle_wolfenstein_operation_resurrection', 'Activision', 'publisher', 'SLUS-20297'),
    ('rise_of_the_kasai', 'Bottlerocket Entertainment', 'developer', 'SCUS-97416'),
    ('rise_of_the_kasai', 'Sony Computer Entertainment', 'publisher', 'SCUS-97416'),
    ('river_king_a_wonderful_journey', 'Marvelous Entertainment Inc', 'developer', 'SLUS-21275'),
    ('river_king_a_wonderful_journey', 'Natsume', 'publisher', 'SLUS-21275'),
    ('rlh_run_like_hell', 'Digital Mayhem', 'developer', 'SLUS-20037'),
    ('rlh_run_like_hell', 'Interplay', 'publisher', 'SLUS-20037'),
    ('robots', 'Eurocom Developments Ltd', 'developer', 'SLUS-20942'),
    ('robots', 'Sierra Entertainment, Inc', 'publisher', 'SLUS-20942'),
    ('rocky', 'Rage Software', 'developer', 'SLUS-20559'),
    ('rocky', 'UbiSoft', 'publisher', 'SLUS-20559'),
    ('rogue_galaxy', 'Level-5', 'developer', 'SCUS-97490'),
    ('rogue_galaxy', 'Sony Computer Entertainment America, Inc', 'publisher', 'SCUS-97490'),
    ('rogue_ops', 'BITS Studios', 'developer', 'SLUS-20746'),
    ('rogue_ops', 'Kemco', 'publisher', 'SLUS-20746'),
    ('rogue_trooper', 'Rebellion', 'developer', 'SLUS-21320'),
    ('rogue_trooper', 'Eidos Interactive', 'publisher', 'SLUS-21320'),
    ('rtx_red_rock', 'Lucasarts', 'developer', 'SLUS-20491'),
    ('rtx_red_rock', 'Lucasarts', 'publisher', 'SLUS-20491'),
    ('rugrats_royal_ransom', 'Avalanche Software', 'developer', 'SLUS-20443'),
    ('rugrats_royal_ransom', 'THQ', 'publisher', 'SLUS-20443'),
    ('rule_of_rose', 'Punchline CG', 'developer', 'SLUS-21448'),
    ('rule_of_rose', 'Atlus', 'publisher', 'SLUS-21448'),
    ('rumble_roses', 'KCET / Yuke''s', 'developer', 'SLUS-20970'),
    ('rumble_roses', 'Konami', 'publisher', 'SLUS-20970'),
    ('rune_viking_warlord', 'Human Head Studios, Inc', 'developer', 'SLUS-20109'),
    ('rune_viking_warlord', 'Take-Two Interactive Software, Inc', 'publisher', 'SLUS-20109'),
    ('rygar_the_legendary_adventure', 'Tecmo', 'developer', 'SLUS-20471'),
    ('rygar_the_legendary_adventure', 'Tecmo', 'publisher', 'SLUS-20471'),
    ('samurai_jack_the_shadow_of_aku', 'Amaze Entertainment', 'developer', 'SLUS-20899'),
    ('samurai_jack_the_shadow_of_aku', 'Sega', 'publisher', 'SLUS-20899'),
    ('samurai_western', 'Acquire', 'developer', 'SLUS-21187'),
    ('samurai_western', 'Atlus USA', 'publisher', 'SLUS-21187'),
    ('scaler', 'Artificial Mind And Move (A2M)', 'developer', 'SLUS-20957'),
    ('scaler', 'Global Star Software', 'publisher', 'SLUS-20957'),
    ('scarface_the_world_is_yours', 'Radical Entertainment', 'developer', 'SLUS-21111'),
    ('scarface_the_world_is_yours', 'Sierra Entertainment', 'publisher', 'SLUS-21111'),
    ('scooby_doo_first_frights', 'Torus Games', 'developer', 'SLUS-21900'),
    ('scooby_doo_first_frights', 'Warner Bros Interactive', 'publisher', 'SLUS-21900'),
    ('scooby_doo_mystery_mayhem', 'Artificial Mind And Move (A2M)', 'developer', 'SLUS-20701'),
    ('scooby_doo_mystery_mayhem', 'THQ', 'publisher', 'SLUS-20701'),
    ('scooby_doo_night_of_100_frights', 'Heavy Iron Studios', 'developer', 'SLUS-20349'),
    ('scooby_doo_night_of_100_frights', 'THQ', 'publisher', 'SLUS-20349'),
    ('scooby_doo_unmasked', 'Artificial Mind And Move (A2M)', 'developer', 'SLUS-21091'),
    ('scooby_doo_unmasked', 'THQ', 'publisher', 'SLUS-21091'),
    ('sd_gundam_force_showdown', 'Tom Create', 'developer', 'SLUS-20698'),
    ('sd_gundam_force_showdown', 'Bandai', 'publisher', 'SLUS-20698'),
    ('second_sight', 'Free Radical Design', 'developer', 'SLUS-21033'),
    ('second_sight', 'Codemasters', 'publisher', 'SLUS-21033'),
    ('secret_agent_clank', 'Sanzaru Games', 'developer', 'SCUS-97623'),
    ('secret_agent_clank', 'Sony', 'publisher', 'SCUS-97623'),
    ('secret_weapons_over_normandy', 'Totally Games', 'developer', 'SLUS-20762'),
    ('secret_weapons_over_normandy', 'Lucasarts', 'publisher', 'SLUS-20762'),
    ('seek_and_destroy', 'Takara', 'developer', 'SLUS-20606'),
    ('seek_and_destroy', 'Conspiracy Entertainment Corporation', 'publisher', 'SLUS-20606'),
    ('sega_classics_collection', 'Sega of Japan', 'developer', 'SLUS-21009'),
    ('sega_classics_collection', 'Sega', 'publisher', 'SLUS-21009'),
    ('seven_samurai_20xx', 'Sammy Studios / Dimps', 'developer', 'SLUS-20621'),
    ('seven_samurai_20xx', 'Sammy Studios', 'publisher', 'SLUS-20621'),
    ('shadow_hearts', 'Forest Entertainment, Inc', 'developer', 'SLUS-20347'),
    ('shadow_hearts', 'Midway Home Entertainment', 'publisher', 'SLUS-20347'),
    ('shadow_hearts_covenant', 'Aruze Corp', 'developer', 'SLUS-21041SLUS-21044'),
    ('shadow_hearts_covenant', 'Midway Home Entertainment', 'publisher', 'SLUS-21041SLUS-21044'),
    ('shadow_of_destiny', 'Konami', 'developer', 'SLUS-20146'),
    ('shadow_of_destiny', 'Konami', 'publisher', 'SLUS-20146'),
    ('shadow_of_rome', 'Capcom', 'developer', 'SLUS-20902'),
    ('shadow_of_rome', 'Capcom', 'publisher', 'SLUS-20902'),
    ('shadow_of_the_colossus', 'Sony', 'developer', 'SCUS-97472'),
    ('shadow_of_the_colossus', 'Sony', 'publisher', 'SCUS-97472'),
    ('shadow_the_hedgehog', 'Sega', 'developer', 'SLUS-21261'),
    ('shadow_the_hedgehog', 'Sega', 'publisher', 'SLUS-21261'),
    ('shaman_king_power_of_spirit', 'Konami Computer Entertainment Japan Co., Ltd. (KCEJ) / Winky Soft', 'developer', 'SLUS-20953'),
    ('shaman_king_power_of_spirit', 'Konami', 'publisher', 'SLUS-20953'),
    ('shaun_white_snowboarding', 'Ubisoft Montreal', 'developer', 'SLUS-21853'),
    ('shaun_white_snowboarding', 'Ubisoft', 'publisher', 'SLUS-21853'),
    ('shin_megami_tensei_nocturne', 'Atlus', 'developer', 'SLUS-20911'),
    ('shin_megami_tensei_nocturne', 'Atlus U.S.A', 'publisher', 'SLUS-20911'),
    ('shin_megami_tensei_persona_3', 'Atlus Co., Ltd', 'developer', 'SLUS-21569'),
    ('shin_megami_tensei_persona_3', 'Atlus U.S.A., Inc', 'publisher', 'SLUS-21569'),
    ('shin_megami_tensei_persona_3_fes', 'Atlus Co., Ltd', 'developer', 'SLUS-21621'),
    ('shin_megami_tensei_persona_3_fes', 'Atlus U.S.A., Inc', 'publisher', 'SLUS-21621'),
    ('shining_force_exa', 'CRI Neverland', 'developer', 'SLUS-21567'),
    ('shining_force_exa', 'Sega', 'publisher', 'SLUS-21567'),
    ('shining_force_neo', 'Neverland Co., Ltd', 'developer', 'SLUS-21206'),
    ('shining_force_neo', 'Sega', 'publisher', 'SLUS-21206'),
    ('shining_tears', 'Amusement Vision / Nextech', 'developer', 'SLUS-21063'),
    ('shining_tears', 'Sega', 'publisher', 'SLUS-21063'),
    ('silent_hill_origins', 'Climax Group', 'developer', 'SLUS-21731'),
    ('silent_hill_origins', 'Konami', 'publisher', 'SLUS-21731'),
    ('silent_hill_shattered_memories', 'Climax Studios Ltd', 'developer', 'SLUS-21899'),
    ('silent_hill_shattered_memories', 'Konami', 'publisher', 'SLUS-21899'),
    ('silent_hill_2', 'Konami Computer Entertainment Tokyo (KCET)', 'developer', 'SLUS-20228'),
    ('silent_hill_2', 'Konami', 'publisher', 'SLUS-20228'),
    ('silent_hill_3', 'Konami Computer Entertainment Tokyo (KCET)', 'developer', 'SLUS-20622'),
    ('silent_hill_3', 'Konami', 'publisher', 'SLUS-20622'),
    ('silent_hill_4_the_room', 'Konami Computer Entertainment Tokyo (KCET)', 'developer', 'SLUS-20873'),
    ('silent_hill_4_the_room', 'Konami', 'publisher', 'SLUS-20873'),
    ('silent_scope', 'Konami', 'developer', 'SLUS-20078'),
    ('silent_scope', 'Konami', 'publisher', 'SLUS-20078'),
    ('silent_scope_2_dark_silhouette', 'Konami Computer Entertainment Tokyo (KCET)', 'developer', 'SLUS-20243'),
    ('silent_scope_2_dark_silhouette', 'Konami', 'publisher', 'SLUS-20243'),
    ('silpheed_the_lost_planet', 'Game Arts', 'developer', 'SLUS-20085'),
    ('silpheed_the_lost_planet', 'Working Designs', 'publisher', 'SLUS-20085'),
    ('singstar_80s', 'SCEE Studio London', 'developer', 'SCUS-97622'),
    ('singstar_80s', 'Sony', 'publisher', 'SCUS-97622'),
    ('siren', 'Sony', 'developer', 'SCUS-97355'),
    ('siren', 'Sony', 'publisher', 'SCUS-97355'),
    ('sitting_ducks', 'Asobo Studio', 'developer', 'SLUS-20886'),
    ('sitting_ducks', 'Hip Games', 'publisher', 'SLUS-20886'),
    ('sky_odyssey', 'Cross Co. Ltd., Future Creates, XAX Entertainment, Inc', 'developer', 'SLUS-20134'),
    ('sky_odyssey', 'Activision', 'publisher', 'SLUS-20134'),
    ('skygunner', 'Sony Computer Entertainment Inc. (Japan)', 'developer', 'SLUS-20384'),
    ('skygunner', 'Atlus USA', 'publisher', 'SLUS-20384'),
    ('sled_storm', 'Electronic Arts Canada', 'developer', 'SLUS-20363'),
    ('sled_storm', 'EA Sports Big', 'publisher', 'SLUS-20363'),
    ('sly_cooper_and_the_thievius_raccoonus', 'Sucker Punch Productions', 'developer', 'SCUS-97198'),
    ('sly_cooper_and_the_thievius_raccoonus', 'Sony Computer Entertainment', 'publisher', 'SCUS-97198'),
    ('sly_2_band_of_thieves', 'Sucker Punch Productions', 'developer', 'SCUS-97316'),
    ('sly_2_band_of_thieves', 'Sony Computer Entertainment', 'publisher', 'SCUS-97316'),
    ('sly_3_honor_among_thieves', 'Sucker Punch Productions', 'developer', 'SCUS-97464'),
    ('sly_3_honor_among_thieves', 'Sony', 'publisher', 'SCUS-97464'),
    ('smash_court_tennis_pro_tournament', 'Namco', 'developer', 'SLUS-20286'),
    ('smash_court_tennis_pro_tournament', 'Namco', 'publisher', 'SLUS-20286'),
    ('smash_court_tennis_pro_tournament_2', 'Namco', 'developer', 'SLUS-20933'),
    ('smash_court_tennis_pro_tournament_2', 'Namco', 'publisher', 'SLUS-20933'),
    ('smuggler_s_run', 'Angel Studios', 'developer', 'SLUS-20065'),
    ('smuggler_s_run', 'Rockstar Games', 'publisher', 'SLUS-20065'),
    ('socom_u_s_navy_seals', 'Zipper Interactive', 'developer', 'SCUS-97230'),
    ('socom_u_s_navy_seals', 'Sony', 'publisher', 'SCUS-97230'),
    ('soldier_of_fortune_gold_edition', 'Pipe Dream Interactive', 'developer', 'SLUS-20084'),
    ('soldier_of_fortune_gold_edition', 'Majesco', 'publisher', 'SLUS-20084'),
    ('sonic_heroes', 'Sonic Team', 'developer', 'SLUS-20718'),
    ('sonic_heroes', 'Sega', 'publisher', 'SLUS-20718'),
    ('sonic_riders', 'Sonic Team', 'developer', 'SLUS-21331'),
    ('sonic_riders', 'Sega', 'publisher', 'SLUS-21331'),
    ('sonic_unleashed', 'Sonic Team', 'developer', 'SLUS-21846'),
    ('sonic_unleashed', 'Sega', 'publisher', 'SLUS-21846'),
    ('soul_calibur_ii', 'Project Soul', 'developer', 'SLUS-20643'),
    ('soul_calibur_ii', 'Namco', 'publisher', 'SLUS-20643'),
    ('soul_calibur_iii', 'Project Soul', 'developer', 'SLUS-21216'),
    ('soul_calibur_iii', 'Namco', 'publisher', 'SLUS-21216'),
    ('soul_nomad_the_world_eaters', 'Nippon Ichi Software Inc', 'developer', 'SLUS-21603'),
    ('soul_nomad_the_world_eaters', 'NIS America', 'publisher', 'SLUS-21603'),
    ('space_channel_5_special_edition', 'United Game Artists (Sega)', 'developer', 'SLUS-20806SLUS-20807'),
    ('space_channel_5_special_edition', 'Agetec / Sega', 'publisher', 'SLUS-20806SLUS-20807'),
    ('space_chimps', 'Brash Entertainment', 'developer', 'SLUS-21783'),
    ('space_chimps', 'Brash Entertainment', 'publisher', 'SLUS-21783'),
    ('sphinx_and_the_cursed_mummy', 'Eurocom Developments Ltd', 'developer', 'SLUS-20482'),
    ('sphinx_and_the_cursed_mummy', 'THQ', 'publisher', 'SLUS-20482'),
    ('spider_man', 'Treyarch Invention, LLC', 'developer', 'SLUS-20336'),
    ('spider_man', 'Activision', 'publisher', 'SLUS-20336'),
    ('spider_man_2', 'Treyarch Invention, LLC', 'developer', 'SLUS-20776'),
    ('spider_man_2', 'Activision', 'publisher', 'SLUS-20776'),
    ('splashdown', 'Rainbow Studios', 'developer', 'SLUS-20223'),
    ('splashdown', 'Atari', 'publisher', 'SLUS-20223'),
    ('spongebob_squarepants_battle_for_bikini_bottom', 'Heavy Iron Studios', 'developer', 'SLUS-20680'),
    ('spongebob_squarepants_battle_for_bikini_bottom', 'THQ', 'publisher', 'SLUS-20680'),
    ('spongebob_squarepants_creature_from_the_krusty_krab', 'Blitz Games', 'developer', 'SLUS-21391'),
    ('spongebob_squarepants_creature_from_the_krusty_krab', 'THQ', 'publisher', 'SLUS-21391'),
    ('spongebob_squarepants_revenge_of_the_flying_dutchman', 'Big Sky Software', 'developer', 'SLUS-20425'),
    ('spongebob_squarepants_revenge_of_the_flying_dutchman', 'THQ', 'publisher', 'SLUS-20425'),
    ('spongebob_squarepants_featuring_nicktoons_globs_of_doom', 'Incinerator Studios LLC', 'developer', 'SLUS-21818'),
    ('spongebob_squarepants_featuring_nicktoons_globs_of_doom', 'THQ', 'publisher', 'SLUS-21818'),
    ('spy_fiction', 'Access Games', 'developer', 'SLUS-20856'),
    ('spy_fiction', 'Sammy Studios', 'publisher', 'SLUS-20856'),
    ('spyro_a_hero_s_tail', 'Eurocom Developments Ltd', 'developer', 'SLUS-20884'),
    ('spyro_a_hero_s_tail', 'Vivendi Universal Games', 'publisher', 'SLUS-20884'),
    ('ssx_3', 'Electronic Arts Canada', 'developer', 'SLUS-20772'),
    ('ssx_3', 'EA Sports Big', 'publisher', 'SLUS-20772'),
    ('star_ocean_till_the_end_of_time', 'tri-Ace', 'developer', 'SLUS-20488SLUS-20891'),
    ('star_ocean_till_the_end_of_time', 'Square Enix', 'publisher', 'SLUS-20488SLUS-20891'),
    ('star_trek_shattered_universe', 'Starsphere Interactive, Inc', 'developer', 'SLUS-20112'),
    ('star_trek_shattered_universe', 'TDK Mediactive, Inc', 'publisher', 'SLUS-20112'),
    ('star_wars_battlefront', 'Pandemic Studios', 'developer', 'SLUS-20898'),
    ('star_wars_battlefront', 'Lucasarts', 'publisher', 'SLUS-20898'),
    ('star_wars_bounty_hunter', 'Lucasarts', 'developer', 'SLUS-20420'),
    ('star_wars_bounty_hunter', 'Lucasarts', 'publisher', 'SLUS-20420'),
    ('star_wars_episode_iii_revenge_of_the_sith', 'The Collective, Inc', 'developer', 'SLUS-21143'),
    ('star_wars_episode_iii_revenge_of_the_sith', 'Lucasarts', 'publisher', 'SLUS-21143'),
    ('star_wars_jedi_starfighter', 'LucasArts Entertainment Company', 'developer', 'SLUS-20293'),
    ('star_wars_jedi_starfighter', 'Lucasarts', 'publisher', 'SLUS-20293'),
    ('star_wars_super_bombad_racing', 'Lucas Learning', 'developer', 'SLUS-20043'),
    ('star_wars_super_bombad_racing', 'Lucasarts', 'publisher', 'SLUS-20043'),
    ('star_wars_the_clone_wars', 'Pandemic Studios', 'developer', 'SLUS-20510'),
    ('star_wars_the_clone_wars', 'Lucasarts', 'publisher', 'SLUS-20510'),
    ('starsky_hutch', 'Minds Eye Productions', 'developer', 'SLUS-20619'),
    ('starsky_hutch', 'Empire Interactive / Global Star Software', 'publisher', 'SLUS-20619'),
    ('state_of_emergency', 'VIS entertainment plc', 'developer', 'SLUS-20214'),
    ('state_of_emergency', 'Rockstar Games', 'publisher', 'SLUS-20214'),
    ('state_of_emergency_2', 'DC Studios, Inc. / VIS entertainment plc', 'developer', 'SLUS-20966'),
    ('state_of_emergency_2', 'Southpeak Interactive', 'publisher', 'SLUS-20966'),
    ('steambot_chronicles', 'Irem Software Engineering, Inc', 'developer', 'SLUS-21344'),
    ('steambot_chronicles', 'Atlus U.S.A., Inc', 'publisher', 'SLUS-21344'),
    ('strawberry_shortcake_the_sweet_dreams_game', 'Eko Software', 'developer', 'SLUS-21497'),
    ('strawberry_shortcake_the_sweet_dreams_game', 'The Game Factory', 'publisher', 'SLUS-21497'),
    ('street_fighter_ex3', 'Arika', 'developer', 'SLUS-20130'),
    ('street_fighter_ex3', 'Capcom', 'publisher', 'SLUS-20130'),
    ('stretch_panic', 'Treasure', 'developer', 'SLUS-20182'),
    ('stretch_panic', 'Conspiracy Entertainment', 'publisher', 'SLUS-20182'),
    ('strike_force_bowling', 'Lab Rats Games', 'developer', 'SLUS-20846'),
    ('strike_force_bowling', 'Crave Entertaiment', 'publisher', 'SLUS-20846'),
    ('sub_rebellion', 'Irem Software Engineering, Inc', 'developer', 'SLUS-20548'),
    ('sub_rebellion', 'Metro3D, Inc', 'publisher', 'SLUS-20548'),
    ('summer_heat_beach_volleyball', 'Acclaim Studios Cheltenham', 'developer', 'SLUS-20634'),
    ('summer_heat_beach_volleyball', 'Acclaim', 'publisher', 'SLUS-20634'),
    ('super_monkey_ball_adventure', 'Traveller''s Tales', 'developer', 'SLUS-21272'),
    ('super_monkey_ball_adventure', 'Sega', 'publisher', 'SLUS-21272'),
    ('super_monkey_ball_deluxe', 'Amusement Vision', 'developer', 'SLUS-20918'),
    ('super_monkey_ball_deluxe', 'Sega', 'publisher', 'SLUS-20918'),
    ('superman_shadow_of_apokolips', 'Infogrames Sheffield House', 'developer', 'SLUS-20235'),
    ('superman_shadow_of_apokolips', 'Atari', 'publisher', 'SLUS-20235'),
    ('swing_away_golf', 'T&E Soft, Inc', 'developer', 'SLUS-20096'),
    ('swing_away_golf', 'Electronic Arts', 'publisher', 'SLUS-20096'),
    ('syphon_filter_the_omega_strain', 'Sony Bend', 'developer', 'SCUS-97264'),
    ('syphon_filter_the_omega_strain', 'Sony', 'publisher', 'SCUS-97264'),
    ('taiko_drum_master', 'Namco Ltd', 'developer', 'SLUS-20800'),
    ('taiko_drum_master', 'Namco', 'publisher', 'SLUS-20800'),
    ('taito_legends', 'Taito', 'developer', 'SLUS-21122'),
    ('taito_legends', 'Sega / Empire Interactive', 'publisher', 'SLUS-21122'),
    ('tak_the_great_juju_challenge', 'Avalanche Software', 'developer', 'SLUS-21218'),
    ('tak_the_great_juju_challenge', 'THQ', 'publisher', 'SLUS-21218'),
    ('tak_2_the_staff_of_dreams', 'Avalanche Software', 'developer', 'SLUS-20952'),
    ('tak_2_the_staff_of_dreams', 'THQ', 'publisher', 'SLUS-20952'),
    ('tak_and_the_guardians_of_gross', 'Blitz Games', 'developer', 'SLUS-21797'),
    ('tak_and_the_guardians_of_gross', 'THQ', 'publisher', 'SLUS-21797'),
    ('tales_of_legendia', 'Namco', 'developer', 'SLUS-21201'),
    ('tales_of_legendia', 'Namco', 'publisher', 'SLUS-21201'),
    ('tales_of_the_abyss', 'Bandai Namco', 'developer', 'SLUS-21386'),
    ('tales_of_the_abyss', 'Bandai Namco', 'publisher', 'SLUS-21386'),
    ('taz_wanted', 'Blitz Games', 'developer', 'SLUS-20236'),
    ('taz_wanted', 'Infogrames', 'publisher', 'SLUS-20236'),
    ('teen_titans', 'Artificial Mind and Movement (A2M)', 'developer', 'SLUS-21183'),
    ('teen_titans', 'THQ / Majesco', 'publisher', 'SLUS-21183'),
    ('teenage_mutant_ninja_turtles', 'Konami', 'developer', 'SLUS-20716'),
    ('teenage_mutant_ninja_turtles', 'Konami', 'publisher', 'SLUS-20716'),
    ('tekken_tag_tournament', 'Namco', 'developer', 'SLUS-20001'),
    ('tekken_tag_tournament', 'Namco', 'publisher', 'SLUS-20001'),
    ('tenchu_wrath_of_heaven', 'K2, LLC', 'developer', 'SLUS-20397'),
    ('tenchu_wrath_of_heaven', 'Activision', 'publisher', 'SLUS-20397'),
    ('terminator_3_rise_of_the_machines', 'Black Ops', 'developer', 'SLUS-20799'),
    ('terminator_3_rise_of_the_machines', 'Atari', 'publisher', 'SLUS-20799'),
    ('tetris_worlds', 'Blue Planet Software', 'developer', 'SLUS-20247'),
    ('tetris_worlds', 'THQ', 'publisher', 'SLUS-20247'),
    ('the_adventures_of_cookie_cream', 'FromSoftware, Inc', 'developer', 'SLUS-20170'),
    ('the_adventures_of_cookie_cream', 'Agetec Inc', 'publisher', 'SLUS-20170'),
    ('the_adventures_of_jimmy_neutron_boy_genius_attack_of_the_twonkies', 'THQ Studio Australia Pty Ltd', 'developer', 'SLUS-20887'),
    ('the_adventures_of_jimmy_neutron_boy_genius_attack_of_the_twonkies', 'THQ', 'publisher', 'SLUS-20887'),
    ('the_ant_bully', 'Artificial Mind And Move (A2M)', 'developer', 'SLUS-21415'),
    ('the_ant_bully', 'Midway / Warner Bros. Interactive Entertainment', 'publisher', 'SLUS-21415'),
    ('the_bard_s_tale', 'InXile Entertainment', 'developer', 'SLUS-20803'),
    ('the_bard_s_tale', 'InXile Entertainment', 'publisher', 'SLUS-20803'),
    ('the_bouncer', 'DreamFactory', 'developer', 'SLUS-20069'),
    ('the_bouncer', 'Square Co. Ltd', 'publisher', 'SLUS-20069'),
    ('the_chronicles_of_narnia_the_lion_the_witch_and_the_wardrobe', 'Traveller''s Tales', 'developer', 'SLUS-21082'),
    ('the_chronicles_of_narnia_the_lion_the_witch_and_the_wardrobe', 'Buena Vista Games Inc.', 'publisher', 'SLUS-21082'),
    ('the_da_vinci_code', 'The Collective, Inc', 'developer', 'SLUS-21443'),
    ('the_da_vinci_code', '2K Games', 'publisher', 'SLUS-21443'),
    ('the_getaway_black_monday', 'SCEE London Studio', 'developer', 'SCUS-97408'),
    ('the_getaway_black_monday', 'Sony', 'publisher', 'SCUS-97408'),
    ('the_godfather', 'EA Redwood Shores', 'developer', 'SLUS-21385'),
    ('the_godfather', 'Electronic Arts', 'publisher', 'SLUS-21385'),
    ('the_golden_compass', 'Shiny Entertaiment', 'developer', 'SLUS-21677'),
    ('the_golden_compass', 'Sega', 'publisher', 'SLUS-21677'),
    ('the_great_escape', 'Pivotal Games', 'developer', 'SLUS-20670'),
    ('the_great_escape', 'Gotham Games', 'publisher', 'SLUS-20670'),
    ('the_lord_of_the_rings_the_return_of_the_king', 'Hypnos Entertainment, Inc', 'developer', 'SLUS-20770'),
    ('the_lord_of_the_rings_the_return_of_the_king', 'Electronic Arts', 'publisher', 'SLUS-20770'),
    ('the_lord_of_the_rings_the_third_age', 'EA Redwood Shores', 'developer', 'SLUS-21027'),
    ('the_lord_of_the_rings_the_third_age', 'Electronic Arts', 'publisher', 'SLUS-21027'),
    ('the_lord_of_the_rings_the_two_towers', 'Stormfront Studios', 'developer', 'SLUS-20578'),
    ('the_lord_of_the_rings_the_two_towers', 'Electronic Arts', 'publisher', 'SLUS-20578'),
    ('the_mummy_returns', 'Blitz Games', 'developer', 'SLUS-20253'),
    ('the_mummy_returns', 'Vivendi Universal Games', 'publisher', 'SLUS-20253'),
    ('the_nightmare_of_druaga_fushigino_dungeon', 'Arika', 'developer', 'SLUS-21071'),
    ('the_nightmare_of_druaga_fushigino_dungeon', 'Namco', 'publisher', 'SLUS-21071'),
    ('the_simpsons_hit_run', 'Radical Entertainment', 'developer', 'SLUS-20624'),
    ('the_simpsons_hit_run', 'Vivendi Universal Games, Inc', 'publisher', 'SLUS-20624'),
    ('the_simpsons_road_rage', 'Radical Entertainment', 'developer', 'SLUS-20305'),
    ('the_simpsons_road_rage', 'Electronic Arts', 'publisher', 'SLUS-20305'),
    ('the_sims_2', 'Maxis', 'developer', 'SLUS-21265'),
    ('the_sims_2', 'Electronic Arts', 'publisher', 'SLUS-21265'),
    ('the_suffering', 'Surreal Software, Inc', 'developer', 'SLUS-20636'),
    ('the_suffering', 'Midway Home Entertainment', 'publisher', 'SLUS-20636'),
    ('the_x_files_resist_or_serve', 'Black Ops Entertainment', 'developer', 'SLUS-20179'),
    ('the_x_files_resist_or_serve', 'Vivendi Universal / Fox Interactive', 'publisher', 'SLUS-20179'),
    ('time_crisis_crisis_zone', 'Namco', 'developer', 'SLUS-20927'),
    ('time_crisis_crisis_zone', 'Namco', 'publisher', 'SLUS-20927'),
    ('timesplitters', 'Free Radical Design', 'developer', 'SLUS-20090'),
    ('timesplitters', 'Eidos Interactive', 'publisher', 'SLUS-20090'),
    ('timesplitters_2', 'Free Radical Design', 'developer', 'SLUS-20314'),
    ('timesplitters_2', 'Eidos Interactive', 'publisher', 'SLUS-20314'),
    ('tom_clancy_s_ghost_recon', 'Red Storm Entertainment, Inc', 'developer', 'SLUS-20613'),
    ('tom_clancy_s_ghost_recon', 'Ubisoft Entertainment', 'publisher', 'SLUS-20613'),
    ('tom_clancy_s_rainbow_six_3', 'Ubi Soft Shanghai', 'developer', 'SLUS-20883'),
    ('tom_clancy_s_rainbow_six_3', 'Ubi Soft', 'publisher', 'SLUS-20883'),
    ('tom_clancy_s_splinter_cell', 'Ubisoft Montreal', 'developer', 'SLUS-20652'),
    ('tom_clancy_s_splinter_cell', 'Ubisoft Entertainment', 'publisher', 'SLUS-20652'),
    ('tony_hawk_s_american_wasteland', 'Neversoft Entertainment', 'developer', 'SLUS-21208'),
    ('tony_hawk_s_american_wasteland', 'Activision', 'publisher', 'SLUS-21208'),
    ('tony_hawk_s_underground', 'Neversoft Entertainment', 'developer', 'SLUS-20731'),
    ('tony_hawk_s_underground', 'Activision', 'publisher', 'SLUS-20731'),
    ('total_overdose_a_gunslinger_s_tale_in_mexico', 'Deadline Games', 'developer', 'SLUS-21283'),
    ('total_overdose_a_gunslinger_s_tale_in_mexico', 'Eidos Interactive', 'publisher', 'SLUS-21283'),
    ('true_crime_new_york_city', 'Luxoflux Corp., Z-Axis, Ltd', 'developer', 'SLUS-21106'),
    ('true_crime_new_york_city', 'Activision', 'publisher', 'SLUS-21106'),
    ('turok_evolution', 'Acclaim Studios Austin', 'developer', 'SLUS-20333'),
    ('turok_evolution', 'Acclaim Entertainment, Inc', 'publisher', 'SLUS-20333'),
    ('twisted_metal_black', 'Incog Inc. Entertainment', 'developer', 'SCUS-97101'),
    ('twisted_metal_black', 'Sony', 'publisher', 'SCUS-97101'),
    ('twisted_metal_black_online', 'Incog Inc. Entertainment', 'developer', 'SCUS-97196'),
    ('twisted_metal_black_online', 'Sony', 'publisher', 'SCUS-97196'),
    ('ty_the_tasmanian_tiger', 'Krome Studios', 'developer', 'SLUS-20571'),
    ('ty_the_tasmanian_tiger', 'Electronic Arts', 'publisher', 'SLUS-20571'),
    ('urban_reign', 'Namco Bandai', 'developer', 'SLUS-21209'),
    ('urban_reign', 'Namco Bandai', 'publisher', 'SLUS-21209'),
    ('vietcong_purple_haze', 'Illusion Softworks', 'developer', 'SLUS-21068'),
    ('vietcong_purple_haze', 'Gathering', 'publisher', 'SLUS-21068'),
    ('wallace_gromit_in_project_zoo', 'Frontier Developments Ltd', 'developer', 'SLUS-20647'),
    ('wallace_gromit_in_project_zoo', 'BAM! Entertainment, Inc', 'publisher', 'SLUS-20647'),
    ('wave_rally', 'Opus Corp', 'developer', 'SLUS-20313'),
    ('wave_rally', 'Eidos Interactive', 'publisher', 'SLUS-20313'),
    ('way_of_the_samurai', 'Acquire Corp', 'developer', 'SLUS-20407'),
    ('way_of_the_samurai', 'Bam Entertainment', 'publisher', 'SLUS-20407'),
    ('we_love_katamari', 'Namco', 'developer', 'SLUS-21230'),
    ('we_love_katamari', 'Namco', 'publisher', 'SLUS-21230'),
    ('whiplash', 'Crystal Dynamics, Inc', 'developer', 'SLUS-20684'),
    ('whiplash', 'Eidos Interactive', 'publisher', 'SLUS-20684'),
    ('wild_arms_alter_code_f', 'Media.Vision Entertainment Inc', 'developer', 'SLUS-20937'),
    ('wild_arms_alter_code_f', 'Agetec, Inc', 'publisher', 'SLUS-20937'),
    ('wild_arms_3', 'Media Vision (Sony)', 'developer', 'SCUS-97203'),
    ('wild_arms_3', 'Sony', 'publisher', 'SCUS-97203'),
    ('without_warning', 'CiRCLE Studio', 'developer', 'SLUS-21156'),
    ('without_warning', 'Capcom', 'publisher', 'SLUS-21156'),
    ('world_championship_poker', 'Coresoft', 'developer', 'SLUS-21028'),
    ('world_championship_poker', 'Crave Entertaiment', 'publisher', 'SLUS-21028'),
    ('world_tour_soccer_2002', 'Team SOHO', 'developer', 'SCUS-97172'),
    ('world_tour_soccer_2002', '989 Sports', 'publisher', 'SCUS-97172'),
    ('worms_3d', 'Team17 Software, Ltd', 'developer', 'SLUS-20894'),
    ('worms_3d', 'Acclaim Entertainment, Inc', 'publisher', 'SLUS-20894'),
    ('wreckless_the_yakuza_missions', 'Activision Studios', 'developer', 'SLUS-20431'),
    ('wreckless_the_yakuza_missions', 'Activision', 'publisher', 'SLUS-20431'),
    ('wta_tour_tennis', 'Konami', 'developer', 'SLUS-20357'),
    ('wta_tour_tennis', 'Konami', 'publisher', 'SLUS-20357'),
    ('wwe_all_stars', 'Subdued Software LLC', 'developer', 'SLUS-21940'),
    ('wwe_all_stars', 'THQ', 'publisher', 'SLUS-21940'),
    ('x_men_next_dimension', 'Paradox Development', 'developer', 'SLUS-20279'),
    ('x_men_next_dimension', 'Activision', 'publisher', 'SLUS-20279'),
    ('xiaolin_showdown', 'Bottlerocket Entertainment', 'developer', 'SLUS-21405'),
    ('xiaolin_showdown', 'Konami', 'publisher', 'SLUS-21405'),
    ('xiii', 'Ubisoft Montreal', 'developer', 'SLUS-20677'),
    ('xiii', 'Ubisoft', 'publisher', 'SLUS-20677'),
    ('yakuza', 'Amusement Vision', 'developer', 'SLUS-21348'),
    ('yakuza', 'Sega', 'publisher', 'SLUS-21348'),
    ('yanya_caballista_city_skater', 'CAVE Co., Ltd', 'developer', 'SLUS-20278'),
    ('yanya_caballista_city_skater', 'Koei Corporation', 'publisher', 'SLUS-20278')
) as b(game_id, company_name, role, source_key)
on conflict (game_id, company_name, role, source) do nothing;

commit;
