-- Second TheGamesDB enrichment pass: covers the next score band (0 <= critic_score < 75,
-- top 340 by critic_score, on a key console/PC platform) using the same targeted,
-- exact-normalized-title-match-only strategy as 20260702190000.
--
-- Idempotent: genre only applies where genre_id is still null, cover only
-- where cover_url is still empty/null.
begin;

with backfill(game_id, genre_id) as (
  values
    ('conan_chop_chop', 'action'),
    ('dungeon_defenders_awakened', 'action'),
    ('mortal_shell_enhanced_edition', 'action'),
    ('vasara_collection', 'shooter'),
    ('death_end_re_quest', 'rpg'),
    ('death_end_re_quest_2', 'rpg'),
    ('formula_one_championship_edition', 'racing'),
    ('god_eater_3', 'action'),
    ('implosion_never_lose_hope', 'action'),
    ('lapis_x_labyrinth', 'action'),
    ('monster_energy_supercross_the_official_videogame_5', 'racing'),
    ('saints_row_the_third_remastered', 'action'),
    ('sam_max_save_the_world', 'adventure'),
    ('sbk_x_superbike_world_championship', 'racing'),
    ('star_ocean_the_last_hope_international', 'rpg'),
    ('the_alliance_alive_hd_remastered', 'rpg'),
    ('the_cruel_king_and_the_great_hero', 'adventure'),
    ('valentino_rossi_the_game', 'racing'),
    ('castlevania_lords_of_shadow_mirror_of_fate_hd', 'action'),
    ('chocobo_s_mystery_dungeon_every_buddy', 'rpg'),
    ('colors_live', 'educational'),
    ('dark_deity', 'adventure'),
    ('disgaea_6_defiance_of_destiny', 'rpg'),
    ('earthlock', 'rpg'),
    ('garden_story', 'action'),
    ('get_even', 'shooter'),
    ('heroland', 'rpg'),
    ('ikenfell', 'strategy'),
    ('infamous_first_light', 'action'),
    ('jonah_lomu_rugby_challenge', 'sports'),
    ('killzone_shadow_fall', 'action'),
    ('kinect_disneyland_adventures', 'action'),
    ('lego_harry_potter_collection', 'action'),
    ('moero_crystal_h', 'rpg'),
    ('project_spark', 'action'),
    ('savage_moon', 'strategy'),
    ('the_takeover', 'action'),
    ('werewolf_the_apocalypse_heart_of_the_forest', 'action'),
    ('anima_gate_of_memories', 'action'),
    ('big_brain_academy_brain_vs_brain', 'puzzle'),
    ('boyfriend_dungeon', 'action'),
    ('control_ultimate_edition_cloud_version', 'action'),
    ('dimension_drive', 'shooter'),
    ('divinity_ii_the_dragon_knight_saga', 'adventure'),
    ('earth_defense_force_5', 'action'),
    ('final_fantasy_type_0_hd', 'action'),
    ('gato_roboto', 'action'),
    ('grandia_hd_collection', 'rpg'),
    ('heavy_rain_move_edition', 'action'),
    ('kingdoms_of_amalur_re_reckoning', 'rpg'),
    ('ninja_gaiden_master_collection', 'action'),
    ('no_more_heroes_heroes_paradise', 'action'),
    ('phoenotopia_awakening', 'action'),
    ('state_of_decay_year_one_survival_edition', 'action'),
    ('trash_panic', 'puzzle'),
    ('wonderbook_book_of_spells', 'adventure'),
    ('morbid_the_seven_acolytes', 'action'),
    ('songbringer', 'action'),
    ('aces_of_the_luftwaffe_squadron', 'shooter'),
    ('assassin_s_creed_rogue_remastered', 'action'),
    ('boulder_dash_xl', 'puzzle'),
    ('collection_of_saga_final_fantasy_legend', 'rpg'),
    ('cyberdimension_neptunia_4_goddesses_online', 'action'),
    ('driveclub', 'racing'),
    ('everything', 'adventure'),
    ('fairy_fencer_f_advent_dark_force', 'rpg'),
    ('fairy_tail', 'rpg'),
    ('flock', 'puzzle'),
    ('knockout_home_fitness', 'sports'),
    ('megadimension_neptunia_vii', 'rpg'),
    ('nba_2k10_draft_combine', 'sports'),
    ('nexomon_extinction', 'rpg'),
    ('spy_chameleon', 'action'),
    ('tribes_of_midgard', 'action'),
    ('zone_of_the_enders_the_2nd_runner_mars', 'platformer'),
    ('ea_sports_ufc', 'fighting'),
    ('below', 'action'),
    ('burgertime_party', 'action'),
    ('god_wars_the_complete_legend', 'rpg'),
    ('king_of_seas', 'action'),
    ('mario_vs_donkey_kong_tipping_stars', 'puzzle'),
    ('my_hero_one_s_justice', 'action'),
    ('nobunaga_s_ambition_taishi', 'strategy'),
    ('road_not_taken', 'puzzle'),
    ('root_film', 'adventure'),
    ('shining_resonance_refrain', 'action'),
    ('the_assembly', 'action'),
    ('the_last_remnant_remastered', 'rpg'),
    ('time_recoil', 'action'),
    ('turrican_flashback', 'action'),
    ('hitman_hd_enhanced_collection', 'action'),
    ('spacebase_startopia', 'strategy'),
    ('sword_of_the_necromancer', 'action'),
    ('akimi_village', 'simulation'),
    ('it_s_quiz_time', 'puzzle'),
    ('kitaria_fables', 'action'),
    ('lost_sphear', 'rpg')
)
update games_library.games g
set genre_id = b.genre_id
from backfill b
where g.game_id = b.game_id
  and g.genre_id is null;

with backfill(game_id, cover_url) as (
  values
    ('castlestorm_definitive_edition', 'https://cdn.thegamesdb.net/images/large/boxart/front/53257-1.jpg'),
    ('mages_of_mystralia', 'https://cdn.thegamesdb.net/images/large/boxart/front/48620-1.jpg'),
    ('resident_evil_6', 'https://cdn.thegamesdb.net/images/large/boxart/front/44226-1.jpg'),
    ('star_ocean_first_departure', 'https://cdn.thegamesdb.net/images/large/boxart/front/12539-1.jpg'),
    ('the_council', 'https://cdn.thegamesdb.net/images/large/boxart/front/65266-1.jpg'),
    ('vasara_collection', 'https://cdn.thegamesdb.net/images/large/boxart/front/68524-1.jpg'),
    ('yesterday_origins', 'https://cdn.thegamesdb.net/images/large/boxart/front/41189-1.jpg'),
    ('anarcute', 'https://cdn.thegamesdb.net/images/large/boxart/front/69214-1.jpg'),
    ('calling_all_cars', 'https://cdn.thegamesdb.net/images/large/boxart/front/66872-1.jpg'),
    ('dance_central_spotlight', 'https://cdn.thegamesdb.net/images/large/boxart/front/37278-1.jpg'),
    ('dance_dance_revolution_universe_game', 'https://cdn.thegamesdb.net/images/large/boxart/front/7170-1.jpg'),
    ('evolve', 'https://cdn.thegamesdb.net/images/large/boxart/front/20646-1.jpg'),
    ('god_eater_3', 'https://cdn.thegamesdb.net/images/large/boxart/front/63351-1.jpg'),
    ('grow_up', 'https://cdn.thegamesdb.net/images/large/boxart/front/37580-1.jpg'),
    ('implosion_never_lose_hope', 'https://cdn.thegamesdb.net/images/large/boxart/front/47750-1.jpg'),
    ('lapis_x_labyrinth', 'https://cdn.thegamesdb.net/images/large/boxart/front/64090-1.jpg'),
    ('lego_the_incredibles', 'https://cdn.thegamesdb.net/images/large/boxart/front/61298-1.jpg'),
    ('nascar_heat_4', 'https://cdn.thegamesdb.net/images/large/boxart/front/68488-1.jpg'),
    ('one_step_from_eden', 'https://cdn.thegamesdb.net/images/large/boxart/front/69528-1.jpg'),
    ('pato_box', 'https://cdn.thegamesdb.net/images/large/boxart/front/63748-1.jpg'),
    ('project_warlock', 'https://cdn.thegamesdb.net/images/large/boxart/front/61640-1.jpg'),
    ('sam_max_save_the_world', 'https://cdn.thegamesdb.net/images/large/boxart/front/54779-1.jpg'),
    ('sbk_x_superbike_world_championship', 'https://cdn.thegamesdb.net/images/large/boxart/front/16431-1.jpg'),
    ('shadow_complex_remastered', 'https://cdn.thegamesdb.net/images/large/boxart/front/40464-1.jpg'),
    ('snake_pass', 'https://cdn.thegamesdb.net/images/large/boxart/front/43482-1.jpg'),
    ('super_stardust_ultra', 'https://cdn.thegamesdb.net/images/large/boxart/front/63173-1.jpg'),
    ('valentino_rossi_the_game', 'https://cdn.thegamesdb.net/images/large/boxart/front/37521-1.jpg'),
    ('zeno_clash_ultimate_edition', 'https://cdn.thegamesdb.net/images/large/boxart/front/36710-1.jpg'),
    ('ninja_gaiden_sigma_2', 'https://cdn.thegamesdb.net/images/large/boxart/front/12489-2.jpg'),
    ('cricket_19', 'https://cdn.thegamesdb.net/images/large/boxart/front/65462-1.jpg'),
    ('disney_infinity_2_0_edition', 'https://cdn.thegamesdb.net/images/large/boxart/front/30972-1.png'),
    ('a_normal_lost_phone', 'https://cdn.thegamesdb.net/images/large/boxart/front/53684-1.jpg'),
    ('agents_of_mayhem', 'https://cdn.thegamesdb.net/images/large/boxart/front/49327-1.jpg'),
    ('bandfuse_rock_legends', 'https://cdn.thegamesdb.net/images/large/boxart/front/21180-1.jpg'),
    ('castlevania_lords_of_shadow_mirror_of_fate_hd', 'https://cdn.thegamesdb.net/images/large/boxart/front/19988-1.jpg'),
    ('cinders', 'https://cdn.thegamesdb.net/images/large/boxart/front/28876-1.png'),
    ('earthlock', 'https://cdn.thegamesdb.net/images/large/boxart/front/55523-1.jpg'),
    ('get_even', 'https://cdn.thegamesdb.net/images/large/boxart/front/64552-1.jpg'),
    ('jonah_lomu_rugby_challenge', 'https://cdn.thegamesdb.net/images/large/boxart/front/53638-1.jpg'),
    ('killzone_shadow_fall', 'https://cdn.thegamesdb.net/images/large/boxart/front/18223-1.jpg'),
    ('kinect_disneyland_adventures', 'https://cdn.thegamesdb.net/images/large/boxart/front/8308-1.jpg'),
    ('mulaka', 'https://cdn.thegamesdb.net/images/large/boxart/front/53624-1.jpg'),
    ('nba_baller_beats', 'https://cdn.thegamesdb.net/images/large/boxart/front/14611-1.jpg'),
    ('pure_farming_2018', 'https://cdn.thegamesdb.net/images/large/boxart/front/64611-1.jpg'),
    ('scene_it_lights_camera_action', 'https://cdn.thegamesdb.net/images/large/boxart/front/12911-1.jpg'),
    ('state_of_mind', 'https://cdn.thegamesdb.net/images/large/boxart/front/60641-1.jpg'),
    ('the_house_of_the_dead_4', 'https://cdn.thegamesdb.net/images/large/boxart/front/27022-1.jpg'),
    ('world_war_z', 'https://cdn.thegamesdb.net/images/large/boxart/front/67829-1.jpg'),
    ('yomawari_the_long_night_collection', 'https://cdn.thegamesdb.net/images/large/boxart/front/61817-1.jpg'),
    ('yono_and_the_celestial_elephants', 'https://cdn.thegamesdb.net/images/large/boxart/front/54486-1.png'),
    ('your_shape_fitness_evolved', 'https://cdn.thegamesdb.net/images/large/boxart/front/15578-1.jpg'),
    ('ancestors_the_humankind_odyssey', 'https://cdn.thegamesdb.net/images/large/boxart/front/67850-1.jpg'),
    ('anima_gate_of_memories', 'https://cdn.thegamesdb.net/images/large/boxart/front/37244-1.jpg'),
    ('axel_pixel', 'https://cdn.thegamesdb.net/images/large/boxart/front/54655-1.jpg'),
    ('bad_north', 'https://cdn.thegamesdb.net/images/large/boxart/front/61142-1.jpg'),
    ('candle_the_power_of_the_flame', 'https://cdn.thegamesdb.net/images/large/boxart/front/61299-1.jpg'),
    ('commanders_attack_of_the_genos', 'https://cdn.thegamesdb.net/images/large/boxart/front/54683-1.jpg'),
    ('dark_devotion', 'https://cdn.thegamesdb.net/images/large/boxart/front/69475-1.jpg'),
    ('dimension_drive', 'https://cdn.thegamesdb.net/images/large/boxart/front/62546-1.jpg'),
    ('divinity_ii_the_dragon_knight_saga', 'https://cdn.thegamesdb.net/images/large/boxart/front/11992-1.jpg'),
    ('ghost_blade_hd', 'https://cdn.thegamesdb.net/images/large/boxart/front/48251-1.jpg'),
    ('grandia_hd_collection', 'https://cdn.thegamesdb.net/images/large/boxart/front/69543-1.jpg'),
    ('massive_chalice', 'https://cdn.thegamesdb.net/images/large/boxart/front/36711-1.png'),
    ('matterfall', 'https://cdn.thegamesdb.net/images/large/boxart/front/53281-1.jpg'),
    ('mirror_s_edge_catalyst', 'https://cdn.thegamesdb.net/images/large/boxart/front/29273-1.jpg'),
    ('mxgp_pro', 'https://cdn.thegamesdb.net/images/large/boxart/front/70686-1.jpg'),
    ('nba_live_18', 'https://cdn.thegamesdb.net/images/large/boxart/front/52379-1.jpg'),
    ('pixeljunk_monsters_2', 'https://cdn.thegamesdb.net/images/large/boxart/front/55643-1.jpg'),
    ('rogue_aces', 'https://cdn.thegamesdb.net/images/large/boxart/front/55114-1.jpg'),
    ('semispheres', 'https://cdn.thegamesdb.net/images/large/boxart/front/47855-1.jpg'),
    ('senko_no_ronde_2', 'https://cdn.thegamesdb.net/images/large/boxart/front/55185-1.jpg'),
    ('smoke_and_sacrifice', 'https://cdn.thegamesdb.net/images/large/boxart/front/55745-1.jpg'),
    ('south_park_let_s_go_tower_defense_play', 'https://cdn.thegamesdb.net/images/large/boxart/front/60330-1.jpg'),
    ('zombi', 'https://cdn.thegamesdb.net/images/large/boxart/front/53253-1.jpg'),
    ('sd_gundam_g_generation_cross_rays', 'https://cdn.thegamesdb.net/images/large/boxart/front/70696-1.jpg'),
    ('sniper_elite_iii', 'https://cdn.thegamesdb.net/images/large/boxart/front/18907-1.jpg'),
    ('aer_memories_of_old', 'https://cdn.thegamesdb.net/images/large/boxart/front/60255-1.jpg'),
    ('amazing_discoveries_in_outer_space', 'https://cdn.thegamesdb.net/images/large/boxart/front/63261-1.jpg'),
    ('bound', 'https://cdn.thegamesdb.net/images/large/boxart/front/41242-1.jpg'),
    ('everything', 'https://cdn.thegamesdb.net/images/large/boxart/front/66506-1.jpg'),
    ('exception', 'https://cdn.thegamesdb.net/images/large/boxart/front/51961-1.png'),
    ('fairy_fencer_f_advent_dark_force', 'https://cdn.thegamesdb.net/images/large/boxart/front/62707-1.jpg'),
    ('flock', 'https://cdn.thegamesdb.net/images/large/boxart/front/15570-1.jpg'),
    ('fragments_of_him', 'https://cdn.thegamesdb.net/images/large/boxart/front/69529-1.jpg'),
    ('hitman_hd_trilogy', 'https://cdn.thegamesdb.net/images/large/boxart/front/14467-1.jpg'),
    ('knight_squad', 'https://cdn.thegamesdb.net/images/large/boxart/front/49080-1.jpg'),
    ('megadimension_neptunia_vii', 'https://cdn.thegamesdb.net/images/large/boxart/front/37575-1.jpg'),
    ('melbits_world', 'https://cdn.thegamesdb.net/images/large/boxart/front/61114-1.jpg'),
    ('membrane', 'https://cdn.thegamesdb.net/images/large/boxart/front/68858-1.jpg'),
    ('nba_2k10_draft_combine', 'https://cdn.thegamesdb.net/images/large/boxart/front/15973-1.jpg'),
    ('pool_panic', 'https://cdn.thegamesdb.net/images/large/boxart/front/65114-1.jpg'),
    ('robonauts', 'https://cdn.thegamesdb.net/images/large/boxart/front/64604-1.jpg'),
    ('spy_chameleon', 'https://cdn.thegamesdb.net/images/large/boxart/front/54068-1.jpg'),
    ('the_hong_kong_massacre', 'https://cdn.thegamesdb.net/images/large/boxart/front/63222-1.jpg'),
    ('the_invisible_hours', 'https://cdn.thegamesdb.net/images/large/boxart/front/55075-1.jpg'),
    ('wwe_legends_of_wrestlemania', 'https://cdn.thegamesdb.net/images/large/boxart/front/13867-1.jpg'),
    ('resident_evil_0_hd_remaster', 'https://cdn.thegamesdb.net/images/large/boxart/front/36947-1.jpg'),
    ('ea_sports_ufc', 'https://cdn.thegamesdb.net/images/large/boxart/front/20746-1.jpg'),
    ('below', 'https://cdn.thegamesdb.net/images/large/boxart/front/54845-1.jpg'),
    ('deadly_premonition_origins', 'https://cdn.thegamesdb.net/images/large/boxart/front/67599-1.jpg'),
    ('elefunk', 'https://cdn.thegamesdb.net/images/large/boxart/front/66535-1.jpg'),
    ('eyepet_move_edition', 'https://cdn.thegamesdb.net/images/large/boxart/front/70141-1.jpg'),
    ('fable_fortune', 'https://cdn.thegamesdb.net/images/large/boxart/front/54862-1.jpg'),
    ('genesis_alpha_one', 'https://cdn.thegamesdb.net/images/large/boxart/front/60832-1.jpg'),
    ('god_wars_the_complete_legend', 'https://cdn.thegamesdb.net/images/large/boxart/front/60834-1.jpg'),
    ('just_cause_4', 'https://cdn.thegamesdb.net/images/large/boxart/front/60181-1.jpg'),
    ('nobunaga_s_ambition_taishi', 'https://cdn.thegamesdb.net/images/large/boxart/front/61991-1.jpg'),
    ('nom_nom_galaxy', 'https://cdn.thegamesdb.net/images/large/boxart/front/54003-1.jpg'),
    ('road_not_taken', 'https://cdn.thegamesdb.net/images/large/boxart/front/22609-1.jpg'),
    ('snooker_19', 'https://cdn.thegamesdb.net/images/large/boxart/front/64332-1.jpg'),
    ('sundered', 'https://cdn.thegamesdb.net/images/large/boxart/front/61919-1.jpg'),
    ('taiko_no_tatsujin_drum_session', 'https://cdn.thegamesdb.net/images/large/boxart/front/65691-1.jpg'),
    ('the_assembly', 'https://cdn.thegamesdb.net/images/large/boxart/front/69526-1.jpg'),
    ('the_godfather_the_don_s_edition', 'https://cdn.thegamesdb.net/images/large/boxart/front/12880-1.jpg'),
    ('the_last_remnant_remastered', 'https://cdn.thegamesdb.net/images/large/boxart/front/61738-1.jpg'),
    ('worms_battlegrounds', 'https://cdn.thegamesdb.net/images/large/boxart/front/25816-1.jpg'),
    ('tracks_the_train_set_game', 'https://cdn.thegamesdb.net/images/large/boxart/front/68307-1.jpg'),
    ('aftercharge', 'https://cdn.thegamesdb.net/images/large/boxart/front/62956-1.jpg'),
    ('akane', 'https://cdn.thegamesdb.net/images/large/boxart/front/68901-1.jpg'),
    ('akimi_village', 'https://cdn.thegamesdb.net/images/large/boxart/front/68293-1.jpg'),
    ('alone_in_the_dark_inferno', 'https://cdn.thegamesdb.net/images/large/boxart/front/35084-1.jpg'),
    ('ao_tennis_2', 'https://cdn.thegamesdb.net/images/large/boxart/front/73428-1.jpg'),
    ('battle_princess_madelyn', 'https://cdn.thegamesdb.net/images/large/boxart/front/62822-1.jpg'),
    ('chromagun', 'https://cdn.thegamesdb.net/images/large/boxart/front/79849-1.jpg'),
    ('danger_zone_2', 'https://cdn.thegamesdb.net/images/large/boxart/front/67884-1.jpg'),
    ('deadlight_director_s_cut', 'https://cdn.thegamesdb.net/images/large/boxart/front/37294-1.jpg'),
    ('disney_magical_world_2_enchanted_edition', 'https://cdn.thegamesdb.net/images/large/boxart/front/95637-1.jpg'),
    ('drive', 'https://cdn.thegamesdb.net/images/large/boxart/front/96071-1.jpg'),
    ('eiyuu_senki_the_world_conquest', 'https://cdn.thegamesdb.net/images/large/boxart/front/50863-1.jpg'),
    ('grip_combat_racing', 'https://cdn.thegamesdb.net/images/large/boxart/front/61882-1.jpg'),
    ('it_s_quiz_time', 'https://cdn.thegamesdb.net/images/large/boxart/front/66973-1.jpg'),
    ('kitaria_fables', 'https://cdn.thegamesdb.net/images/large/boxart/front/88054-1.jpg'),
    ('knack_2', 'https://cdn.thegamesdb.net/images/large/boxart/front/49037-1.jpg'),
    ('lost_sphear', 'https://cdn.thegamesdb.net/images/large/boxart/front/108068-1.jpg'),
    ('madden_nfl_21', 'https://cdn.thegamesdb.net/images/large/boxart/front/76330-1.jpg'),
    ('mario_sonic_at_the_olympic_games_tokyo_2020', 'https://cdn.thegamesdb.net/images/large/boxart/front/65349-1.jpg')
)
update games_library.games g
set cover_url = b.cover_url
from backfill b
where g.game_id = b.game_id
  and (g.cover_url = '' or g.cover_url is null);

commit;
